<?php 
    $display = [];
    if(isset($this->displays)){
        $display = $this->displays;
    }
    // display css
    echo isset($display['style']) ? ("<style>" . $display['style'] . "</style>") : "";
?>

<div style="text-align:center"><img alt="" src="/uploads/root/logo1.jpg" style="width:60px" />&nbsp; &nbsp;<img alt="" src="/uploads/root/eta.jpg" style="width:60px" /><br />
	<div style="color:#305496; font-size:10px;font-family:Arial,Helvetica,sans-serif" >
		<strong>SAGEN GROUP PHÂN PHỐI ĐỘC QUYỀN THƯƠNG HIỆU ETIAXIL</strong><br />
		<strong>TẠI THỊ TRƯỜNG VIỆT NAM.</strong><br />
		<strong><span style="color:red">MỌI HÀNH VI GIẢ MẠO SẼ ĐƯỢC XỬ LÝ THEO QUY ĐỊNH PHÁP LUẬT</span></strong>
	</div>
</div>
<br />
<div style="text-align:center">
	<div style="font-size:10px"><span style="font-family:Arial,Helvetica,sans-serif"><span style="color:#305496"><strong>C&Ocirc;NG TY C&Ocirc;̉ PH&Acirc;̀N THƯƠNG MẠI VÀ DỊCH VỤ SAGEN</strong><br />
	ĐỊA CHỈ: 62 Đường 31C, Phường An Phú, Th&agrave;nh Phố Thủ Đức,<br />Th&agrave;nh Phố H&ocirc;̀ Chí Minh, Việt Nam.<br />
	HOTLINE: 0282 203 0808</span></span>
	</div>
</div>



<!-- <div style="text-align:center"><span style="color:#305496"><span style="font-size:10px"><strong>CÔNG TY CỔ PHẦN THƯƠNG MẠI VÀ DỊCH VỤ SAGEN</strong><br />
			ĐỊA CHỈ: 62 Đường 31C, Phường An Phú, Thành Phố Thủ Đức, Thành Phố Hồ Chí Minh, Việt Nam.<br />
			HOTLINE: 0282 203 0808</span></span></div> -->

<div style="text-align:center"><span style="color:#305496"><span style="font-size:9px"><strong>CHÀO MỪNG KHÁCH HÀNG XÁC THỰC SẢN PHẨM ETIAXIL CHÍNH HÃNG</span></strong></span></div>

<div style="text-align:center"><span style="color:#305496"><span style="font-size:9px"><strong>*Các thông tin sau chỉ được sử dụng để chăm sóc và bảo vệ quyền lợi khách hàng</span></strong></span></div>
	
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100 p-t-0 p-b-5">
    		<?php $this->form->prepare(); ?>
            <?= $this->form()->openTag($this->form) ?>
            <div class="wrap-input100 validate-input m-t-0 m-b-0">
                <?= $this->formElement($this->form->get('fullname')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('fullname')) ?></div>
            </div>
            <div class="wrap-input100 validate-input m-t-0 m-b-0">
                <?= $this->formElement($this->form->get('phone')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('phone')) ?></div>
            </div>
            <div class="wrap-input100 validate-input m-t-0 m-b-0">
                <?= $this->formElement($this->form->get('code')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('code')) ?></div>
            </div>
			
			<div style="text-align:center"><span style="color:#305496"><span style="font-size:9px"><strong>(Vui lòng cào lớp phủ bạc trên tem để lấy Mã Xác Thực, có giá trị xác thực một lần duy nhất)</span></strong></span></div>
				
			<div class="container-login100-form-btn">
				<?= $this->formRow($this->form->get('btnSubmit')) ?>
			</div>
        	<?=$this->form()->closeTag($this->form)?>
		</div>
	</div>
</div>

<div class="container">
	<div style="text-align:left"><span style="font-size:10px"><span style="color:#305496"><strong>Li&ecirc;n hệ Etiaxil Vietnam để được hỗ trợ:&nbsp;</strong></span><br />
		<span style="color:#000000"><strong>WEBSITE</strong></span>&nbsp;<a href="https://etiaxil.com.vn"><span style="font-size:10px"><span style="color:#0563c1">https://etiaxil.com.vn</span></span></a></span><br />
		<strong><span style="font-size:10px"><span style="color:#000000">FANPAGE</span></span></strong>&nbsp;<a href="https://facebook.com/etiaxilvietnam"><span style="font-size:10px"><span style="color:#0563c1">https://facebook.com/etiaxilvietnam</span></span></a></p>
	</div>
</div>


			


<div class = "container">
<div style="text-align:center; background-color:#002060; color:#FFFFFF"><span style="font-size:10px"><strong>DANH MỤC SẢN PHẨM ETIAXIL</strong></span></div>
<br />
<table border="1" cellpadding="5" cellspacing="5" style="width:100%">
	<tbody>
		<tr style="background-color:#002060; color:#FFFFFF">
			<td style="text-align:center"><span style="font-size:10px"><strong>STT</strong></span></td>
			<td style="text-align:center"><span style="font-size:10px"><strong>H&Igrave;NH ẢNH</strong></span></td>
			<td style="text-align:center"><span style="font-size:10px"><strong>D&Ograve;NG SẢN PHẨM ĐẶC TRỊ</strong></span></td>
		</tr>
		
		<tr>
			<td style="text-align:center"><span style="font-size:10px">1</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/da_sieu_nhay_cam_15ml_nau-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/dac-tri/"><span style="font-size:10px">LĂN KHỬ M&Ugrave;I NGĂN MỒ H&Ocirc;I D&Agrave;NH CHO DA SI&Ecirc;U NHẠY CẢM (M&Agrave;U N&Acirc;U) 15ML&nbsp;</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">2</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/lan_khu_mui_da_nhay_cam_xanh-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/dac-tri/"><span style="font-size:10px">LĂN KHỬ M&Ugrave;I NGĂN MỒ H&Ocirc;I D&Agrave;NH CHO DA NHẠY CẢM (M&Agrave;U XANH) 15ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">3</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/lan_khu_mui_da_thuong_do-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/dac-tri/"><span style="font-size:10px">LĂN KHỬ M&Ugrave;I NGĂN MỒ H&Ocirc;I D&Agrave;NH CHO DA THƯỜNG (M&Agrave;U ĐỎ) 15ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">4</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/dac-tri-mo-hoi-chan_nhay-cam.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/dac-tri/"><span style="font-size:10px">KHỬ M&Ugrave;I ETIAXL ĐẶC TRỊ MỒ H&Ocirc;I CH&Acirc;N D&Agrave;NH CHO DA NHẠY CẢM 100ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">5</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/dac-tri-mo-hoi-chan_da-thuong.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/dac-tri/"><span style="font-size:10px">KHỬ M&Ugrave;I ETIAXIL ĐẶC TRỊ MỒ H&Ocirc;I CH&Acirc;N D&Agrave;NH CHO DA THƯỜNG 100ML</span></a></td>
		</tr>
		
		<tr>
			<td colspan="3">&nbsp;</td>
		</tr>
		<tr style="background-color:#002060; color:#FFFFFF">
			<td style="text-align:center"><span style="font-size:10px"><strong>STT</strong></span></td>
			<td style="text-align:center"><span style="font-size:10px"><strong>H&Igrave;NH ẢNH</strong></span></td>
			<td style="text-align:center"><span style="font-size:10px"><strong>D&Ograve;NG SẢN PHẨM H&Agrave;NG NG&Agrave;Y</strong></span></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">1</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/_eta_-roll_on-removebg-preview.png" style="width:20px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">KHỬ M&Ugrave;I H&Agrave;NG NG&Agrave;Y DẠNG LĂN ETIAXIL 50ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">2</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/khu_mui_hang_ngay_xit-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">KHỬ M&Ugrave;I H&Agrave;NG NG&Agrave;Y DẠNG XỊT 100ML (ETIAXIL DEODORANT 48H SPRAY)</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">3</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/khu_mui_hang_ngay_phun_suong-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">KHỬ M&Ugrave;I H&Agrave;NG NG&Agrave;Y DẠNG PHUN SƯƠNG 150ML (ETIAXIL DEODORANT 48H AEROSOL)</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">4</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/khu_mui_hang_ngay_sap-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">KHỬ M&Ugrave;I H&Agrave;NG NG&Agrave;Y DẠNG S&Aacute;P ETIAXIL 40ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">5</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/khu_mui_chan_xit_100ml-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">KHỬ M&Ugrave;I CH&Acirc;N DẠNG XỊT 100ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">6</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/lan_khu_mui_chuyen_biet_50ml-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">LĂN KHỬ M&Ugrave;I NGĂN MỒ H&Ocirc;I CHUY&Ecirc;N BIỆT ETIAXIL DEODORANT DOUCEUR 48H ROLL-ON 50ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">7</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/sap_khu_mui_chuyen_biet_48h_40ml-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">S&Aacute;P KHỬ M&Ugrave;I NGĂN MỒ H&Ocirc;I CHUY&Ecirc;N BIỆT ETIAXIL DEODORANT DOUCEUR 48H STICK 40ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">8</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/khu_mui_chuyen_biet_phun_suong_49h-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">XỊT PHUN SƯƠNG KHỬ M&Ugrave;I NGĂN MỒ H&Ocirc;I CHUY&Ecirc;N BIỆT ETIAXIL DEODORANT DOUCEUR 48H A&Eacute;ROSOL 150ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">9</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/khu_mui_nha_dam_xit-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">XỊT KHỬ M&Ugrave;I NGĂN MỒ H&Ocirc;I CHIẾT XUẤT NHA ĐAM ETIAXIL DEODORANT VEGETAL 24H SPRAY SANS GAZ 100ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">10</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/khu_mui_nha_dam-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/hang-ngay/"><span style="font-size:10px">LĂN KHỬ M&Ugrave;I NGĂN MỒ H&Ocirc;I CHIẾT XUẤT NHA ĐAM ETIAXIL DEODORANT VEGETAL 24H ROLL-ON- 50ML</span></a></td>
		</tr>
		<tr>
			<td colspan="3">&nbsp;</td>
		</tr>
		<tr style="background-color:#002060; color:#FFFFFF">
			<td style="text-align:center"><span style="font-size:10px"><strong>STT</strong></span></td>
			<td style="text-align:center"><span style="font-size:10px"><strong>H&Igrave;NH ẢNH</strong></span></td>
			<td style="text-align:center"><span style="font-size:10px"><strong>D&Ograve;NG SẢN PHẨM DẦU GỘI V&Agrave; SỮA TẮM</strong></span></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">1</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/dau_goi-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/lam-sach-co-the/"><span style="font-size:10px">DẦU GỘI L&Agrave;M SẠCH V&Agrave; ĐIỀU TIẾT B&Atilde; NHỜN ETIAXIL DEO-SHAMPOOING 24H 150ML</span></a></td>
		</tr>
		<tr>
			<td style="text-align:center"><span style="font-size:10px">2</span></td>
			<td style="text-align:center"><span style="font-size:10px"><img alt="" src="/uploads/root/gel_tam-removebg-preview.png" style="width:50px" /></span></td>
			<td><a href="https://etiaxil.com.vn/mua/lam-sach-co-the/"><span style="font-size:10px">GEL TẮM L&Agrave;M SẠCH V&Agrave; KHỬ M&Ugrave;I 2 IN 1 ETIAXIL D&Eacute;O-DOUCHE 24H 200ML</span></a></td>
		</tr>
	</tbody>
</table>
</div>