<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Thông tin truy xuất')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="<?= TEMPS_01 ?>images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>css/util.css">
	<link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>css/main.css">
<!--===============================================================================================-->
    </head>
	<body style="margin: 0px; padding: 0px;width:100%;">
            <?= $this->content ?>

<!--===============================================================================================-->
	<script src="<?= TEMPS_01 ?>vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="<?= TEMPS_01 ?>vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="<?= TEMPS_01 ?>vendor/bootstrap/js/popper.js"></script>
	<script src="<?= TEMPS_01 ?>vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="<?= TEMPS_01 ?>vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="<?= TEMPS_01 ?>vendor/daterangepicker/moment.min.js"></script>
	<script src="<?= TEMPS_01 ?>vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="<?= TEMPS_01 ?>vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	</body>
</html>
