<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Thông tin truy xuất')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <link rel="stylesheet" type="text/css" href="<?= TEMPS_01 ?>fonts/font-awesome-4.7.0/css/font-awesome.min.css">
        <style>
            body{margin: 0px; padding: 0px; font-family: Arial, Helvetica, sans-serif;}
        </style>
    </head>
	<body>
    	<?= $this->content ?>
	</body>
</html>
