<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Truy cập bị từ chối!')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']) ?>
    	
        <link href="<?= TEMPLATE_PRO ?>assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?= TEMPLATE_PRO ?>main/css/style.css" rel="stylesheet">
        <link href="<?= TEMPLATE_PRO ?>main/css/pages/error-pages.css" rel="stylesheet">
        <link href="<?= TEMPLATE_PRO ?>main/css/colors/default-dark.css" id="theme" rel="stylesheet">
    </head>
    
    <body class="fix-header card-no-border fix-sidebar">
    	tu choi truy cap
	</body>
    <script src="<?= TEMPLATE_PRO ?>assets/plugins/jquery/jquery.min.js"></script>
    <script src="<?= TEMPLATE_PRO ?>assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="<?= TEMPLATE_PRO ?>assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?= TEMPLATE_PRO ?>main/js/waves.js"></script>
</html>
