<?php
$title = "Thêm khen thưởng, kỷ luật";
$this->headTitle($title);
?>
<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= TEMPS ?>app-assets/vendors/css/forms/selects/select2.min.css">
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'index']) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                        		
                                <?= $this->form()->openTag($this->form) ?>
                              	<div class="form-group col-md-12">
                                 	<?= $this->formLabel($this->form->get('profile_id')) ?>
                                  	<?= $this->formElement($this->form->get('profile_id')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('profile_id')) ?></div>
                              	</div>
                              	<div class="form-group col-md-6">
                                 	<?= $this->formLabel($this->form->get('group_id')) ?>
                                  	<?= $this->formElement($this->form->get('group_id')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('group_id')) ?></div>
                              	</div>
                              	<div class="form-group col-md-6">
                                  	<?= $this->formLabel($this->form->get('date')) ?>
                                  	<?= $this->formElement($this->form->get('date')) ?>
                                  	<div class="text-danger"><?= $this->formElementErrors($this->form->get('date')) ?></div>
                              	</div>
                                
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('content')) ?>
                                    <?= $this->formElement($this->form->get('content')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('content')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('type')) ?>
                                    <?= $this->formElement($this->form->get('type')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('type')) ?></div>
                                </div>
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('proposal')) ?>
                                    <?= $this->formElement($this->form->get('proposal')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('proposal')) ?></div>
                                </div>
								<div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('level')) ?>
                                    <?= $this->formElement($this->form->get('level')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('level')) ?></div>
                                </div>
                                <div class="form-group col-md-12 text-center">
                                    <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                </div>
                                
                                <?= $this->form()->closeTag($this->form) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function () {
	$('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss'
   	});
	$('input[name=type]').on('change',function(){
		var getType = $(this).attr('id');
		var type = "Mức " + $(`label[for = ${getType}]`).text();
		$(`label[for = level]`).text(type);
		$('#level').attr('placeholder', type)
	})
});
</script>
