<?php
$title = "Thêm số điện thoại";
$this->headTitle($title);
?>
<?php include_once("/../../layout/layout-admin/script-address.php"); ?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'index', 'id' => $this->userId]) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                    			<?php $this->form->prepare(); ?>
                            	<?= $this->form()->openTag($this->form) ?>
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('phone')) ?>
                                    <?= $this->formElement($this->form->get('phone')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('phone')) ?></div>
                                </div>
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('status')) ?>
                                    <div class="demo-radio-button">
                                    <?= $this->formElement($this->form->get('status')) ?>
                                    </div>
                                </div>
                                <div class="form-group col-md-12 text-center">
                                    <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                </div>
                                <?= $this->form()->closeTag($this->form) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>