<?php
$title = "Yêu cầu phép";
$this->headTitle($title);
$date = \Pxt\Datetime\ChangeDatetime::getDateCurrent();
$currentName = $this->currentName;
/* số năm, số tháng, số ngày */
// $date1 = date_create("2008-10-14");
// $date2 = date_create("2021-10-13");
// $dateDifference = date_diff($date1, $date2)->format('%y năm, %m tháng and %d ngày');
// echo date_diff($date1, $date2)->format("%y"). "<br>";
// echo $dateDifference;

/* tính số ngày */
// $a = strtotime("2021-10-13");
// $b = strtotime("2021-10-17");
// echo round(($b - $a)/(60*60*24));
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                    <a title="Thêm dữ liệu" href="javascript:void(0)" class="btn btn-success pxt-modal" data-toggle="modal" data-target="#defaultSize"
                        route="<?= $this->url('persons/leave-requests', ['action' => 'add']) ?>">
                        <i class="la la-plus-circle"></i>Thêm dữ liệu</a>
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
                    <div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>

                                <div class="form-group col-md-4">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-1">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>

                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <th class="text-center">Họ tên</th>
                                                <th class="text-center">Nghỉ phép từ ngày</th>
                                                <th class="text-center">Nghỉ phép tới ngày</th>
                                                <th class="text-center">Số ngày nghỉ</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrLeaveRequests->getAdapter()->count() > 0){
                                                $optionProfileName = $this->optionProfileName;
                                                $optionProfileStartDate = $this->optionProfileStartDate;
                                                $i = 1;
                                                foreach($this->arrLeaveRequests as $item){
                                                    // echo date_format(date_create($optionProfileStartDate[$item['profile_id']]), "Y-m-d");
                                        ?>
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                            	<td class="align-middle"><?= $optionProfileName[$item['profile_id']] ?></td>
                                                <td class="text-center align-middle"><?= date_format(date_create($item['leave_start_date']), 'd/m/Y') ?>  <?= ($item['option_leave_start_date']!=0)? "(".\Persons\Model\LeaveRequests::getOption()[$item['option_leave_start_date']].")" : "" ?></td>
                                                <td class="text-center align-middle"><?= date_format(date_create($item['leave_stop_date']), 'd/m/Y') ?>  <?= ($item['option_leave_stop_date']!=0)? "(".\Persons\Model\LeaveRequests::getOption()[$item['option_leave_stop_date']].")" : "" ?></td>
                                                <td class="text-center align-middle"><?= $item['total_apply_leave'] ?></td>
                                                <td class="text-center align-middle">
                                                    <a title="Xóa ngày phép '<?= $optionProfileName[$item['profile_id']]; ?>'?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('persons/leave-requests', ['action' => 'delete', 'user_id'=> $item['user_id'], 'id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrLeaveRequests,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'persons/leave-requests', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>