<link rel="stylesheet" type="text/css" href="<?= TEMPS ?>app-assets/css/core/colors/palette-tooltip.min.css">
<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<?php
$title = "Đánh giá";
$this->headTitle($title);
$dataPoint = $this->dataPoint;
$dataEvaluation = [];
if(isset($this->dataEvaluation)){
    $dataEvaluation = $this->dataEvaluation;
}
$valuePost = $this->valuePost;
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'index']) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                        		<?php $this->form->prepare(); ?>
                                <?= $this->form()->openTag($this->form) ?>
                                <div class="form-group col-md-4">
                                    <?= $this->formLabel($this->form->get('year')) ?>
                                    <?= $this->formElement($this->form->get('year')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('year')) ?></div>
                                </div><br>
                               
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black submit-form-inputs dataTable">
                                        <thead>
                                            <tr>
                                                <th class="text-center align-middle" style="width:5%">STT</th>
                                                <th class="text-center" style="width:30%">Tiêu chí</th>
                                                <th class="text-center align-middle" >Điểm</th>
                                                <th class="text-center align-middle">Biểu hiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                            if(!empty($dataEvaluation)){
                                                $i=1;
                                                foreach($dataEvaluation as $key => $item){
                                                    // \Zend\Debug\Debug::dump($dataEvaluation);
                                        ?>
                                            <tr>
                                                <th class="text-center align-middle"><?= $i++ ?></th>
                                            	<td class="text-left align-middle" data-toggle="tooltip" data-placement="left" title="<?= $item['description']; ?>"><label for="<?= $key ?>"><?= $item['name'] ?></label></td>
                                            	<td class="text-left align-middle">
                                                    <!-- <?//= $this->formElement($this->form->get($key."[point]")) ?>
                                                    <div class="text-danger"><?//= $this->formElementErrors($this->form->get($key."[point]")) ?></div> -->
                                                    <select name="<?= $key."[point]" ?>" class="title_tooltip form-control" data-original-title="" title="">
                                                        <option <?= ($valuePost[$key]["point"] == 'NA' ? "selected" : '') ?> value="NA" title="Không áp dụng">NA</option>
                                                        <option <?= ($valuePost[$key]["point"] == '1' ? "selected" : '') ?> value="1" title="Không đạt">1</option>
                                                        <option <?= ($valuePost[$key]["point"] == '2' ? "selected" : '') ?> value="2" title="Đạt">2</option>
                                                        <option <?= ($valuePost[$key]["point"] == '3' ? "selected" : '') ?> value="3" title="Tốt">3</option>
                                                        <option <?= ($valuePost[$key]["point"] == '4' ? "selected" : '') ?> value="4" title="Rất tốt">4</option>
                                                        <option <?= ($valuePost[$key]["point"] == '5' ? "selected" : '') ?> value="5"  title="Xuất sắc">5</option>
                                                    </select>
                                                </td>
                                            	<td class="text-left align-middle">
                                                    <!-- <?//= $this->formElement($this->form->get($key."[expression]")) ?>
                                                    <div class="text-danger"><?//= $this->formElementErrors($this->form->get($key."[expression]")) ?></div> -->
                                                    <textarea name="<?= $key."[expression]" ?>" class="form-control" placeholder="Biểu hiện "><?= ($valuePost[$key]["expression"] !=='' ? $valuePost[$key]["expression"] : '') ?></textarea>
                                                </td>
                                            </tr>
                                        <?php
                                                }
                                            }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="form-group col-md-12">
                                  	<?= $this->formLabel($this->form->get('personal_comment')) ?>
                                  	<?= $this->formElement($this->form->get('personal_comment')) ?>
                                  	<div class="text-danger"><?= $this->formElementErrors($this->form->get('personal_comment')) ?></div>
                              	</div>
                                <div class="form-group col-md-12 text-center">
                                    <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                </div>
                                <?= $this->form()->closeTag($this->form) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<script src="<?= TEMPS ?>app-assets/js/scripts/tooltip/tooltip.min.js"></script>

<script type="text/javascript">
$(function () {
	$('.datetimepicker-input').datetimepicker({
        view: 'years',
       	format: 'YYYY'
   	});

    $(".title_tooltip").change(function(event) {
        $.each($(this).find('option'), function(key, value) {
            $(value).removeClass('active');
        })
        $('option:selected').addClass('active');
    });
    $(".title_tooltip").tooltip({
        placement: 'right',
        trigger: 'hover',
        container: 'body',
        title: function(e) {
            return $(this).find('.active').attr('title');
        }
    });
});
</script>