<link rel="stylesheet" type="text/css" href="<?= TEMPS ?>app-assets/css/core/colors/palette-tooltip.min.css">
<?php
$title = "Thêm sản phẩm";
$this->headTitle($title);
$dataPoint = $this->dataPoint;
$dataEvaluation = [];
if(isset($this->dataEvaluation)){
    $dataEvaluation = $this->dataEvaluation;
}
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'index']) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                        		<?php $this->form->prepare(); ?>
                                <?= $this->form()->openTag($this->form) ?>
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black submit-form-inputs dataTable">
                                        <thead>
                                            <tr>
                                                <th class="text-center align-middle">STT</th>
                                                <th class="text-center" style="width:25%">Tiêu chí</th>
                                                <th class="text-center">Điểm</th>
                                                <th class="text-center align-middle">Biểu hiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                            if(!empty($dataEvaluation)){
                                                $i=1;
                                                foreach($dataEvaluation as $key => $item){
                                        ?>
                                            <tr>
                                                <td class="text-center align-middle"><?= $i++ ?></td>
                                            	<td class="text-left align-middle" data-toggle="tooltip" data-placement="left" title="<?= $item['description']; ?>"><label for="<?= $key ?>"><?= $item['name'] ?></label></td>
                                                <td class="text-center align-middle"><?= $this->formElement($this->form->get("point")) ?></td>
                                                <td class="text-center align-middle"><?= $this->formElement($this->form->get("expression")) ?></td>
                                            </tr>
                                        <?php
                                                }
                                            }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
        
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('general_comment')) ?>
                                    <?= $this->formElement($this->form->get('general_comment')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('general_comment')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('personal_comment')) ?>
                                    <?= $this->formElement($this->form->get('personal_comment')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('personal_comment')) ?></div>
                                </div>
                                <div class="form-group col-md-12 text-center">
                                    <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                </div>
                                <?= $this->form()->closeTag($this->form) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<script src="<?= TEMPS ?>app-assets/js/scripts/tooltip/tooltip.min.js"></script>