<?= $this->doctype() ?>

<html">

<head>
	<meta charset="utf-8">
	<title>Đăng nhập</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="<?= TEMPS ?>app-assets/images/logo/favicon.png">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="<?= TEMPS_LOGIN ?>css/bootstrap.min.css">
	<!-- Fontawesome CSS -->
	<link rel="stylesheet" href="<?= TEMPS_LOGIN ?>css/fontawesome-all.min.css">
	<!-- Flaticon CSS -->
	<link rel="stylesheet" href="<?= TEMPS_LOGIN ?>font/flaticon.css">
	<!-- Google Web Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="<?= TEMPS_LOGIN ?>style.css">
</head>

<body>

<?= $this->content ?>
	<!-- jquery-->
	<script src="<?= TEMPS_LOGIN ?>js/jquery-3.5.0.min.js"></script>
	<!-- Popper js -->
	<script src="<?= TEMPS_LOGIN ?>js/popper.min.js"></script>
	<!-- Bootstrap js -->
	<script src="<?= TEMPS_LOGIN ?>js/bootstrap.min.js"></script>
	<!-- Imagesloaded js -->
	<script src="<?= TEMPS_LOGIN ?>js/imagesloaded.pkgd.min.js"></script>
	<!-- Validator js -->
	<script src="<?= TEMPS_LOGIN ?>js/validator.min.js"></script>
	<!-- Custom Js -->
	<script src="<?= TEMPS_LOGIN ?>js/main.js"></script>

</body>

</html>
