<?php
$title = "Chuyển cho người phụ trách";
$this->headTitle($title);
?>
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-body">
            <div class="row">

                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h2 class="card-title text-center" style="font-size: 24px; font-weight: bold">Thông tin trúng thưởng</h2>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body">
                                <table class="table">
                                    <tbody>
                                        <tr>
                                            <td class="align-middle"><strong>Số điện thoại trúng thưởng: </strong></td>
                                            <td class="align-middle"><?= $valueCurrent["phone_id"] ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Chương trình khuyến mãi: </strong></td>
                                            <td class="align-middle"><?= isset($optionPromotions[$valueCurrent["promotion_id"]]) ? $optionPromotions[$valueCurrent["promotion_id"]] : "" ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Ngày trúng: </strong></td>
                                            <td class="align-middle"><?= $valueCurrent["created_at"] ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Danh sách mã trúng thưởng: </strong></td>
                                            <td class="align-middle">
                                                <?php
                                                foreach ($arrCodeInWin as $item) {
                                                    echo "- " . $item["code_id"] . " (" . $item["created_at"] . ")";
                                                    echo ($item["phone_root"] != "") ? (" - Được nhắn bởi sđt: " . $item["phone_root"]) : "";
                                                    echo "<br />";
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Người phụ trách: </strong></td>
                                            <td class="align-middle"><?= isset($optionUsers[$valueCurrent["user_input"]]) ? $optionUsers[$valueCurrent["user_input"]] : "Không xác định" ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Số điện thoại nhận thưởng: </strong></td>
                                            <td class="align-middle"><?= $valueCurrent["phone_recipient"] ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Tên người nhận thưởng: </strong></td>
                                            <td class="align-middle"><?= $valueCurrent["fullname_recipient"] ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Địa chỉ nhận thưởng: </strong></td>
                                            <td class="align-middle"><?= $valueCurrent["address_recipient"] ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Phần thưởng: </strong></td>
                                            <td class="align-middle"><?= isset($optionProducts[$valueCurrent["product_id"]]) ? $optionProducts[$valueCurrent["product_id"]] : "Không xác định" ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Ghi chú từ người chuyển thông tin: </strong></td>
                                            <td class="align-middle"><?= $valueCurrent["note_1"] ?></td>
                                        </tr>
                                        <tr>
                                            <td class="align-middle"><strong>Ghi chú từ người nhập thông tin: </strong></td>
                                            <td class="align-middle"><?= $valueCurrent["note_2"] ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h1 class="card-title text-center" style="font-size: 28px; font-weight: bold">Cập nhật thông tin trả thưởng</h1>
                        </div>
                        <?php
                        if ($valueCurrent["status_order"] == 1) {
                        ?>
                            <div class="card-content collapse show">
                                <div class="card-body text-center">
                                    <h4><strong class="text-success">Đã hoàn thành trả thưởng</strong></h4>
                                </div>
                            </div>
                        <?php
                        } else {
                        ?>
                            <div class="card-content collapse show">
                                        <?php $this->form->prepare(); ?>
                                        <?= $this->form()->openTag($this->form) ?>
                                <div class="card-body">
                                    <div class="row mx-5">
                                        <div class="form-group col-6">
                                            <?= $this->formLabel($this->form->get('code_order')) ?>
                                            <?= $this->formElement($this->form->get('code_order')) ?>
                                            <div class="text-danger"><?= $this->formElementErrors($this->form->get('code_order')) ?></div>
                                        </div>
                                        <div class="form-group col-6">
                                            <?= $this->formLabel($this->form->get('finished_at')) ?>
                                            <?= $this->formElement($this->form->get('finished_at')) ?>
                                            <div class="text-danger"><?= $this->formElementErrors($this->form->get('finished_at')) ?></div>
                                        </div>
                                        <div class="form-group col-md-12 col-12">
                                            <?= $this->formLabel($this->form->get('note_3')) ?>
                                            <?= $this->formElement($this->form->get('note_3')) ?>
                                            <div class="text-danger"><?= $this->formElementErrors($this->form->get('note_3')) ?></div>
                                        </div>
                                        <div class="form-group col-md-12 text-center">
                                            <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                        </div>
                                    </div>
                                </div>
                                        <?= $this->form()->closeTag($this->form) ?>
                            </div>
                        <?php
                        }
                        ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<script type="text/javascript" src="<?= TEMPS ?>assets/moment.js/2.22.2/moment-with-locales.min.js"></script>
<script type="text/javascript" src="<?= TEMPS ?>assets/moment-timezone/0.5.21/moment-timezone-with-data-2012-2022.min.js"></script>
<script src="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/js/tempusdominus-bootstrap-4.js"></script>

<script type="text/javascript">
$(function () {
	$('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss'
   	});
});
</script>
