<?php
$title = "Thêm sản phẩm";
$this->headTitle($title);

$settingDatas = [];
if(isset($this->settingDatas)){
    $settingDatas = $this->settingDatas;
}
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'index']) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                        		<?php $this->form->prepare(); ?>
                                <?= $this->form()->openTag($this->form) ?>
                              	<div class="form-group col-md-12">
                                 	<?= $this->formLabel($this->form->get('code')) ?>
                                  	<?= $this->formElement($this->form->get('code')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('code')) ?></div>
                              	</div>
                              	<div class="form-group col-md-12">
                                 	<?= $this->formLabel($this->form->get('barcode')) ?>
                                  	<?= $this->formElement($this->form->get('barcode')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('barcode')) ?></div>
                              	</div>
                              	<div class="form-group col-md-12">
                                  	<?= $this->formLabel($this->form->get('name')) ?>
                                  	<?= $this->formElement($this->form->get('name')) ?>
                                  	<div class="text-danger"><?= $this->formElementErrors($this->form->get('name')) ?></div>
                              	</div>
                              	<div class="form-group col-md-12">
                                 	<?= $this->formLabel($this->form->get('status')) ?>
                                  	<div class="demo-radio-button">
                                  	<?= $this->formElement($this->form->get('status')) ?>
                                	</div>
                              	</div>
                                
                                <?php 
                                    if(isset($this->userId) && $this->userId == "1"){
                                ?>
                                    <div class="form-group col-md-12">
                                    	<?= $this->formLabel($this->form->get('prefix_code')) ?>
                                     	<?= $this->formElement($this->form->get('prefix_code')) ?>
                                      	<div class="text-danger"><?= $this->formElementErrors($this->form->get('prefix_code')) ?></div>
                                  	</div>
                                  	<div class="form-group col-md-12">
                                       	<?= $this->formLabel($this->form->get('prefix_serial')) ?>
                                      	<?= $this->formElement($this->form->get('prefix_serial')) ?>
                                     	<div class="text-danger"><?= $this->formElementErrors($this->form->get('prefix_serial')) ?></div>
                                 	</div>
                                  	<div class="form-group col-md-12">
                                       	<?= $this->formLabel($this->form->get('serial_begin')) ?>
                                      	<?= $this->formElement($this->form->get('serial_begin')) ?>
                                     	<div class="text-danger"><?= $this->formElementErrors($this->form->get('serial_begin')) ?></div>
                                 	</div>
                                  	<div class="form-group col-md-12">
                                       	<?= $this->formLabel($this->form->get('message_success')) ?>
                                      	<?= $this->formElement($this->form->get('message_success')) ?>
                                     	<div class="text-danger"><?= $this->formElementErrors($this->form->get('message_success')) ?></div>
                                 	</div>
									 <div class="form-group col-md-12">
                                       	<?= $this->formLabel($this->form->get('message_invalid')) ?>
                                      	<?= $this->formElement($this->form->get('message_invalid')) ?>
                                     	<div class="text-danger"><?= $this->formElementErrors($this->form->get('message_invalid')) ?></div>
                                 	</div>
                                  	<div class="form-group col-md-12">
                                       	<?= $this->formLabel($this->form->get('message_checked')) ?>
                                      	<?= $this->formElement($this->form->get('message_checked')) ?>
                                     	<div class="text-danger"><?= $this->formElementErrors($this->form->get('message_checked')) ?></div>
                                 	</div>
                                  	<div class="form-group col-md-12">
                                       	<?= $this->formLabel($this->form->get('message_outdate')) ?>
                                      	<?= $this->formElement($this->form->get('message_outdate')) ?>
                                     	<div class="text-danger"><?= $this->formElementErrors($this->form->get('message_outdate')) ?></div>
                                 	</div>
                                    <?php 
                                    }
                                       if(!empty($settingDatas)){
                                           foreach($settingDatas as $key => $item){
											   if($item["type"] == "Image"){
									?>
									<div class="form-group col-md-12">
										<img width="100px" src="<?= (isset($this->valuePost[$key . "_hidden"]) && $this->valuePost[$key . "_hidden"] != "") ? $this->valuePost[$key . "_hidden"] : "/img/upload.png" ?>"
										id="<?= $key ?>" value_id="src" id_hidden="<?= $key ?>_hidden" value_hidden="value" class="pxt-uploads-default" />
										<?= $this->formElement($this->form->get($key . '_hidden')) ?>
									</div>
									<?php
											   }else{
                                    ?>
                                    <div class="form-group col-md-12">
                                    	<?= $this->formLabel($this->form->get($key)) ?>
                                    	<?= $this->formElement($this->form->get($key)) ?>
                                    	<div class="text-danger"><?= $this->formElementErrors($this->form->get($key)) ?></div>
                                    </div>
									<?php 
											   }
                                            }
                                        }
                                    ?>
                                
                              	<div class="form-group col-md-12">
                                  	<?= $this->formLabel($this->form->get('description')) ?>
                                  	<?= $this->formElement($this->form->get('description')) ?>
                                  	<div class="text-danger"><?= $this->formElementErrors($this->form->get('description')) ?></div>
                              	</div>
                                <div class="form-group col-md-12 text-center">
                                    <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                </div>
                                
                                <?= $this->form()->closeTag($this->form) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<script src="<?= TEMPS ?>assets/ckeditor/full/ckeditor.js"></script>
<script src="<?= TEMPS ?>assets/ckfinder/ckfinder.js"></script>
<script>
CKEDITOR.replace( 'description' , {
        height: 400,
		allowedContent: true,
		extraPlugins: 'ckawesome',
    } );
<?php 
if(!empty($settingDatas)){
    foreach($settingDatas as $key => $item){
        if($item['type'] == "Textarea"){
            echo "CKEDITOR.replace( '" . $key . "' );";
        }
    }
}
?>
</script>