
<?php
$title = "Quản lý sản phẩm";
$this->headTitle($title);
$contentManages = $this->contentManages;
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                    <a class="pxt-modal btn btn-success" title="Thêm dữ liệu" href="<?= $this->url($this->route, ['action' => 'add']) ?>">
                      		Thêm dữ liệu
                    </a>
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>
                                <?php if(isset($this->userId) && $this->userId == '1'){ ?>
                                <div class="form-group col-md-4">
                                    <?= $this->formElement($this->formSearch->get('company_id')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('company_id')) ?></div>
                                </div>
                                <?php } ?>
                                <div class="form-group col-md-4">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-4">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <?php if($this->userId == "1"){ ?><th class="text-center">Công ty</th><?php } ?>
                                                <?php 
                                                    foreach($contentManages as $key => $itemManage){
                                                ?>
                                                <th class="text-center"><?= $itemManage['name'] ?></th>
                                                <?php 
                                                    }
                                                ?>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrProducts->getAdapter()->count() > 0){
                                                $i = 1;
                                                $optionCompanies = $this->optionCompanies;
                                                foreach($this->arrProducts as $item){
                                                    $datas = json_decode($item['datas'], true);
                                                    if(!empty($datas)){
                                                        foreach($datas as $key => $itemData){
                                                            $item[$key] = $itemData;
                                                        }
                                                    }
                                                    //$item = $item + $datas;
                                                    //\Zend\Debug\Debug::dump($item);
                                        ?>
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                            	<?php if($this->userId == "1"){ ?><td class="align-middle"><?= isset($optionCompanies[$item['company_id']]) ? $optionCompanies[$item['company_id']] : "Không xác định"; ?></td><?php } ?>
                                                <?php 
                                                    foreach($contentManages as $keyManage => $itemManage){
                                                        if($itemManage['type'] == 'Image'){
                                                                $image = "/img/image.png";
                                                                if( isset($item[$keyManage]) && $item[$keyManage] != "" && !is_array($item[$keyManage]) ){
                                                                    $image = $item[$keyManage];
                                                                }
                                                ?> 
                                                    <td class="text-center align-middle">
                                                        <img src="<?= $image ?>" width="100px"/>
                                                	</td>
                                            	<?php }elseif($itemManage['type'] == 'Datetime'){ ?>
                                                	<td class="text-center align-middle"><?= $item[$keyManage] ?></td>
                                            	<?php }else{ ?>
                                                	<td class="align-middle"><?= $item[$keyManage] ?></td>
                                                <?php }} ?>
                                                <td class="text-center align-middle">
                                                    <a title="Sửa dữ liệu" class="pxt-modal" href="<?= $this->url('storehouses/products', ['action' => 'edit', 'id' => $item['id']]) ?>">
    													<i class="la la-pencil"></i></a>
                                                    <a title="Bạn muốn xóa '<?= $item['name']; ?>'?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('storehouses/products', ['action' => 'delete', 'id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrProducts,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'storehouses/products', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
