<?php
$title = 'Danh sách tài khoản';
$this->headTitle($title);
?>
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-header row mb-1">
            <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
                <h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
                <div class="row breadcrumbs-top d-inline-block">
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                            <li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                            <li class="breadcrumb-item active">Danh sách</li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                    <a class="btn btn-success pxt-modal" title="Thêm dữ liệu" href="<?= $this->url($this->route, ['action' => 'add']) ?>">
                        <i class="la la-plus-circle"></i> Thêm dữ liệu
                    </a>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body">
                                <?php $this->formSearch->prepare(); ?>
                                <?= $this->form()->openTag($this->formSearch) ?>
                                <div class="form-group col-md-10">
                                    <?= $this->formElement($this->formSearch->get('keyword')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                                </div>
                                <div class="form-group col-md-2">
                                    <?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                                </div>
                                <?= $this->form()->closeTag($this->formSearch) ?>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-content show">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <th class="text-center">Tài khoản CRM</th>
                                                <th class="text-center">Tên CRM</th>
                                                <th class="text-center">Thông tin tài khoản fortune</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            if ($this->arrUserCrms->getAdapter()->count() > 0) {
                                                $optionUsers = $this->optionUsers;
                                                $i = 1;
                                                foreach ($this->arrUserCrms as $item) {
                                            ?>
                                                    <tr>
                                                        <td class="text-center"><?= $i++; ?></td>
                                                        <td><?= $item['id']; ?></td>
                                                        <td><?= $item['name']; ?></td>
                                                        <td><?= isset($optionUsers[$item['user_id']]) ? $optionUsers[$item['user_id']] : "Không xác định" ?></td>
                                                        <td class="text-center">
                                                            <a title="Sửa tài khoản '<?= $item['id']; ?>'?" href="<?= $this->url('admin/user-crms', ['action' => 'edit', 'id' => $item['id']]) ?>">
                                                                <i class="la la-pencil"></i></a>
                                                            <a title="Bạn muốn xóa tài khoản '<?= $item['id']; ?>'?" href="javascript:void(0)" data-toggle="modal" 
                                                            data-target="#defaultSize" class="pxt-modal" route="<?= $this->url('admin/user-crms', ['action' => 'delete', 'id' => $item['id']]) ?>">
                                                                <i class="la la-close"></i></a>
                                                        </td>
                                                    </tr>
                                                <?php
                                                }
                                            } else {
                                                ?>
                                                <tr>
                                                    <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                                </tr>
                                            <?php
                                            }
                                            ?>
                                        </tbody>
                                        <?= $this->paginationControl(
                                            $this->arrUserCrms,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'admin/user-crms', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>