<?php
$title = "Tạo khuyến mãi tích điểm";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'index']) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                				<?= $this->partial("promotions/index/add-nav-tabs.phtml", ['route' => 'promotions/index', 'id' => 'add-score']) ?>
                               	<div class="tab-content">
                                   	<div class="tab-pane active" id="add-score" role="tabpanel">
                                     	<div class="p-20">
                                     		<?php $this->form->prepare(); ?>
                                     		<?= $this->form()->openTag($this->form) ?>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('name')) ?>
                                                <?= $this->formElement($this->form->get('name')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('name')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('dial')) ?>
                                                <div class="demo-radio-button">
                                                <?= $this->formElement($this->form->get('dial')) ?>
                                                </div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('datetime_begin')) ?>
                                                <?= $this->formElement($this->form->get('datetime_begin')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('datetime_begin')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('datetime_end')) ?>
                                                <?= $this->formElement($this->form->get('datetime_end')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('datetime_end')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('description')) ?>
                                                <?= $this->formElement($this->form->get('description')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('description')) ?></div>
                                            </div>
                                            <?php 
                                                if(!empty($this->arrProducts)){
                                                    $valuePost = $this->valuePost;
                                            ?>
                                            <div class="form-group col-md-12">
                                            	<label for="products_id">Sản phẩm sẽ tham gia chương trình: </label><br />
                                                <div class="table-responsive m-t-10">
                                                    <table class="display nowrap table table-hover table-striped" cellspacing="0" width="100%">
                                                        <tbody>
                                                        <?php
                                                            foreach($this->arrProducts as $key => $item){
                                                        ?>
                                                            <tr>
                                                                <td class="align-middle"><?= $item ?></td>
                                                            	<td class="align-middle">
                                                            		<input type="text" name="score-<?= $key ?>" id="score-<?= $key ?>" class="form-control" value="<?= (isset($valuePost['score-' . $key]) ? $valuePost['score-' . $key] : '0') ?>"
                                                            			placeholder="0">
                                                            	</td>
                                                            </tr>
                                                        <?php
                                                            }
                                                        ?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            <?php 
                                                }
                                            ?>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('status')) ?>
                                                <div class="demo-radio-button">
                                                <?= $this->formElement($this->form->get('status')) ?>
                                                </div>
                                            </div>
											<div class="form-group col-md-3">
												<?= $this->formElement($this->form->get('supplie_id')) ?>
												<div class="text-danger"><?= $this->formElementErrors($this->form->get('supplie_id')) ?></div>
											</div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('limit_win')) ?>
                                                <?= $this->formElement($this->form->get('limit_win')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('limit_win')) ?></div>
                                            </div>
											
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('limit_message_day')) ?>
                                                <?= $this->formElement($this->form->get('limit_message_day')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('limit_message_day')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_limit_day')) ?>
                                                <?= $this->formElement($this->form->get('message_limit_day')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_limit_day')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('limit_message_month')) ?>
                                                <?= $this->formElement($this->form->get('limit_message_month')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('limit_message_month')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_limit_month')) ?>
                                                <?= $this->formElement($this->form->get('message_limit_month')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_limit_month')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('price_topup')) ?>
                                                <?= $this->formElement($this->form->get('price_topup')) ?>
                                                <small class="font-italic">Nạp tiền trực tiếp vào điện thoại hoặc thông qua </small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('price_topup')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('score_win')) ?>
                                                <?= $this->formElement($this->form->get('score_win')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('score_win')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_near_win')) ?>
                                                <?= $this->formElement($this->form->get('message_near_win')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_near_win')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_win')) ?>
                                                <?= $this->formElement($this->form->get('message_win')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_win')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_limit_win')) ?>
                                                <?= $this->formElement($this->form->get('message_limit_win')) ?>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_limit_win')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12 text-center">
                                                <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                            </div>
                                            <?= $this->form()->closeTag($this->form) ?>
                                     	</div>
                                  	</div>
                             	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<!-- <script type="text/javascript" src="<?= TEMPS ?>assets/moment.js/2.22.2/moment-with-locales.min.js"></script>
<script type="text/javascript" src="<?= TEMPS ?>assets/moment-timezone/0.5.21/moment-timezone-with-data-2012-2022.min.js"></script>
<script src="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/js/tempusdominus-bootstrap-4.js"></script> -->
<script src="<?= TEMPS ?>/assets/ckeditor/standard/ckeditor.js"></script>
<script type="text/javascript">
CKEDITOR.replace( 'description' );
$(function () {
	$('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss'
   	});
});
</script>