<?php 
    $this->form->prepare();
    $this->form()->addValidAttribute('route');
    $checkRelationship = $this->checkRelationship;
?>
       	<?= $this->form()->openTag($this->form) ?>
        <?php
        if(!empty($checkRelationship)){
        ?>
        <div class="form-group col-md-12">
        	<?= isset($checkRelationship['list_promotions']) ? "- Chương trình '" . $this->valueCurrent['name'] . "' đang liên kết với danh sách tham gia khuyến mãi, nếu xóa thì tất cả danh sách sẽ bị xóa!<br />" : "" ?>
        	<?= isset($checkRelationship['winner_promotions']) ? "- Chương trình '" . $this->valueCurrent['name'] . "' đang liên kết với danh sách trúng thưởng, nếu xóa thì tất cả danh sách sẽ bị xóa!<br />" : "" ?>
        	<?= isset($checkRelationship['promotions_products']) ? "- Chương trình '" . $this->valueCurrent['name'] . "' đang liên kết với danh sách sản phẩm, nếu xóa thì tất cả danh sách sẽ bị xóa!<br />" : "" ?>
        	<?= isset($checkRelationship['list_dials']) ? "- Chương trình '" . $this->valueCurrent['name'] . "' đang liên kết với danh sách tham gia quay số, nếu xóa thì tất cả danh sách sẽ bị xóa!<br />" : "" ?>
        	<?= isset($checkRelationship['dials_promotions']) ? "- Chương trình '" . $this->valueCurrent['name'] . "' đang liên kết với một vài chương trình quay số, nếu xóa thì tất cả liên kết sẽ bị xóa!<br />" : "" ?>
		</div>
        <div class="form-group col-md-12 text-center">
    		<h3>Bạn có muốn xoá?</h3>
		</div>
        <?php
        }
        ?>
        <div class="form-group col-md-12 text-center">
    		<button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    		<?= $this->formRow($this->form->get('btnSubmit')) ?>
		</div>
        <?=$this->form()->closeTag($this->form)?>


