<?php
$title = "Quản lý điểm cộng";
$this->headTitle($title);
?>
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-header row mb-1">
            <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
                <h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
                <div class="row breadcrumbs-top d-inline-block">
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                            <li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                            <li class="breadcrumb-item active">Danh sách</li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                    <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Tính năng
                    </button>
                    <div class="dropdown-menu arrow">
                        <a class="dropdown-item pxt-modal" title="Thêm dữ liệu"
                           href="<?= $this->url($this->route, ['action' => 'addPlusScore']) ?>">
                            <i class="la la-plus-circle"></i> Thêm dữ liệu
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">

                        </div>
                    </div>
                    <div class="card">
                        <div class="card-content show">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                        <tr>
                                            <th class="text-center">STT</th>
                                            <th>Điểm cộng</th>
                                            <th class="text-center">Tin nhắn thắng</th>
                                            <th class="text-center">Sự kiện</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        if (!empty($this->arrayPlusScore)) {
                                            foreach ($this->arrayPlusScore as $item => $value) {
                                                ?>
                                                <tr>
                                                    <td class="align-middle text-center"><?= $item ?></td>
                                                    <td class="align-middle"><?= $value['score']; ?></td>
                                                    <td class="align-middle"><?= $value['message_win']; ?></td>
                                                    <td class="align-middle text-center">
                                                        <a title="Sửa dữ liệu" href="<?= $this->url('promotions/index', ['action' => 'editPlusScore', 'id' => $value['id']]) ?>">
                                                            <i class="la la-pencil"></i></a>
                                                        <a title="Bạn muốn xóa điểm thắng ?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                           route="<?= $this->url('promotions/index', ['action' => 'deletePlusScore', 'id' => $value['id']]) ?>">
                                                            <i class="la la-close"></i></a>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                        } else {
                                            ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var height = $(window).height(); // New height
    var width = $(window).width(); // New width
    $(function () {
        $(".pxt-dial").click(function () {
            window.open($(this).attr("href"), "myWindow", "width=" + (width * 0.9) + ", height=" + (height * 0.9));
            return false;
        });
    });
</script>