<?php
$title = "Sửa khóa đào tạo";
$this->headTitle($title);
$this->form->prepare();
$this->form()->addValidAttribute('route');
$valueCurrent = $this->valueCurrent;
?>
<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= TEMPS ?>app-assets/vendors/css/forms/selects/select2.min.css">
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item active"><?= $valueCurrent['name'] ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                        		
                                <?= $this->form()->openTag($this->form) ?>
                              	<div class="form-group col-md-12">
                                 	<?= $this->formLabel($this->form->get('name')) ?>
                                  	<?= $this->formElement($this->form->get('name')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('name')) ?></div>
                              	</div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('trainer')) ?>
                                    <?= $this->formElement($this->form->get('trainer')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('trainer')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('participants')) ?>
                                    <?= $this->formElement($this->form->get('participants')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('participants')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                 	<?= $this->formLabel($this->form->get('date')) ?>
                                  	<?= $this->formElement($this->form->get('date')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('date')) ?></div>
                              	</div>
                              	<div class="form-group col-md-6">
                                  	<?= $this->formLabel($this->form->get('location')) ?>
                                  	<?= $this->formElement($this->form->get('location')) ?>
                                  	<div class="text-danger"><?= $this->formElementErrors($this->form->get('location')) ?></div>
                              	</div>
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('content')) ?>
                                    <?= $this->formElement($this->form->get('content')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('content')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('document')) ?>
                                    <?= $this->formElement($this->form->get('document')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('document')) ?></div>
                                </div>
                                    <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('fee')) ?>
                                    <?= $this->formElement($this->form->get('fee')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('fee')) ?></div>
                                </div>
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('other_info')) ?>
                                    <?= $this->formElement($this->form->get('other_info')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('other_info')) ?></div>
                                </div>
                                <div class="form-group col-md-12 text-center">
                                    <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                </div>
                                
                                <?= $this->form()->closeTag($this->form) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<script src="<?= TEMPS ?>assets/pxt.js"></script>
<script src="<?= TEMPS ?>app-assets/vendors/js/forms/select/select2.full.min.js"></script>
<script src="<?= TEMPS ?>app-assets/js/scripts/forms/select/form-select2.min.js"></script>
<script type="text/javascript">
$(function () {
	$('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss'
   	});
    $('.select2').select2({placeholder:"Người tham gia:", dropdownParent: $('#xlarge')});
});
</script>

<!-- <script src="<?= TEMPS ?>assets/ckeditor/full/ckeditor.js"></script>
<script src="<?= TEMPS ?>assets/ckfinder/ckfinder.js"></script>
<script>
CKEDITOR.replace( 'description' , {
        height: 400
    } );
<?php 
if(!empty($settingDatas)){
    foreach($settingDatas as $key => $item){
        if($item['type'] == "Textarea"){
            echo "CKEDITOR.replace( '" . $key . "' );";
        }
    }
}
?>
</script> -->