<?php
$title = "Quản lý đào tạo";
$this->headTitle($title);
$datetimeCurrent = \Pxt\Datetime\ChangeDatetime::getDatetimeCurrent();

?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                      	<a class="btn btn-success pxt-modal" href="<?= $this->url('persons/trainings', ['action' => 'add']) ?>" title="Thêm dữ liệu">
                      		<i class="la la-plus-circle"></i> Thêm dữ liệu
                      	</a>
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>

                                <div class="form-group col-md-4">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-1">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>

                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center" style="width: 5%">STT</th>
                                                <th class="text-center" style="width: 15%">Tên khóa đào tạo</th>
                                                <th class="text-center" style="width: 10%">Thời gian</th>
                                                <th class="text-center">Địa điểm</th>
                                                <th class="text-center" style="width: 15%">Người tham gia</th>
                                                <th class="text-center">Người đào tạo</th>
                                                <th class="text-center" style="width: 20%">Nội dung</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrTrainings->getAdapter()->count() > 0){
                                                $optionProfile = $this->optionProfile;
                                                $i = 1;
                                                
                                                foreach($this->arrTrainings as $item){
                                                    $arrParticipant = [];
                                                    $y = 0;
                                                    foreach(explode(", ",$item['participants']) as $participant){
                                                        $arrParticipant[$y] = $optionProfile[$participant];
                                                        $y++;
                                                    }
                                        ?>
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                            	<td class="align-middle"><?= $item['name'] ?></td>
                                                <td class="text-center align-middle"><?= $item['date']?><br><?= ($item['date'] > $datetimeCurrent)? "" : "(<span class='text-warning'>Hết hạn</span>)" ?></td>
                                                <td class="text-center align-middle"><?= $item['location'] ?></td>
                                                <td class="align-middle"><?= implode(", ",$arrParticipant) ?></td>
                                                <td class="text-center align-middle"><?= $item['trainer'] ?></td>
                                                <td class="align-middle" data-toggle="tooltip" data-placement="left" title="<?= $item['content']; ?>">
                                                    <?= Pxt\String\ChangeString::shortcutString($item['content'], 20) ?>
                                                </td>
                                                <td class="text-center align-middle">
                                                    <a title="Sửa dữ liệu" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                    	route="<?= $this->url('persons/trainings', ['action' => 'edit', 'id' => $item['id']]) ?>">
    													<i class="la la-pencil"></i></a>
                                                    <a title="Bạn muốn xóa ?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('persons/trainings', ['action' => 'delete', 'id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrTrainings,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'persons/trainings', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>