<?php 
    $companyCurrent = [];
    if(isset($this->companyCurrent)){
        $companyCurrent = $this->companyCurrent;
    }
    $settingDisplay = [];
    if(isset($this->settingDisplay)){
        $settingDisplay = $this->settingDisplay;
    }
    // display css
    echo isset($settingDisplay['style']) ? ("<style>" . $settingDisplay['style'] . "</style>") : "";
    if(isset($this->infoDisplay)){
        echo $this->infoDisplay;
    }
?>