<?php 
    $display = [];
    if(isset($this->displays)){
        $display = $this->displays;
    }
    // display css
    echo isset($display['style']) ? ("<style>" . $display['style'] . "</style>") : "";
    $arrCode = $this->arrCode;
    $arrProduct=$this->arrProduct;
?>  

<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100 p-t-0 p-b-5">
            <div class="text-center align-middle" style="font-size: 30px;"><?= $arrCode['ttkh']; ?></div>
            <div class="text-center align-middle" style="font-size: 30px;"><?= $arrCode['voucher'] ?></div>
            <hr>
    		<?php $this->form->prepare(); ?>
            <?= $this->form()->openTag($this->form) ?>
           
            <div class="wrap-input100 validate-input m-t-0 m-b-0">
                <?= $this->formElement($this->form->get('code')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('code')) ?></div>
            </div>
				
			<div class="container-login100-form-btn">
				<?= $this->formRow($this->form->get('btnSubmit')) ?>
			</div>
        	<?=$this->form()->closeTag($this->form)?>
		</div>
	</div>
</div>

<?=$arrProduct['description'];?>