<?php 
    $this->form->prepare();
    $this->form()->addValidAttribute('route');
?>
<?= $this->form()->openTag($this->form) ?>

<div class="form-group col-md-12">
    <?= $this->formLabel($this->form->get('name')) ?>
    <?= $this->formElement($this->form->get('name')) ?>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('name')) ?></div>
</div>
<div class="form-group col-md-12">
    <?= $this->formLabel($this->form->get('file')) ?>
    <?= $this->formElement($this->form->get('file')) ?>
    <p class= "description">Chỉ được upload file có định dạng 'jpg','png','jpeg', 'pdf'</p>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('file')) ?></div>
</div>
<div class="form-group col-md-12">
    <?= $this->formLabel($this->form->get('group_id')) ?>
    <?= $this->formElement($this->form->get('group_id')) ?>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('group_id')) ?></div>
</div>

<div class="form-group col-md-12 text-center">
    <button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    <?= $this->formRow($this->form->get('btnSubmit')) ?>
</div>
<?=$this->form()->closeTag($this->form)?>