<?php
$title = "Quản lý khối mã PIN";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                  	<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tính năng</button>
                  	<div class="dropdown-menu arrow">
                      	<a class="dropdown-item pxt-modal" title="Thêm dữ liệu" href="<?= $this->url($this->route, ['action' => 'add']) ?>" >
                      		<i class="la la-plus-circle"></i> Thêm dữ liệu
                      	</a>
                      	<a class="dropdown-item pxt-modal" href="javascript:void(0)" title="Thêm mã PIN dự trữ" 
                      		route="<?= $this->url('codes/index', ['action' => 'add-pin']) ?>" data-toggle="modal" data-target="#defaultSize">
                      		<i class="la la-plus-circle"></i> Thêm mã PIN dự trữ
                      	</a>
                      	<a class="dropdown-item pxt-modal" href="javascript:void(0)" title="Thêm QRCode dự trữ" 
                      		route="<?= $this->url('codes/index', ['action' => 'add-qrcode']) ?>" data-toggle="modal" data-target="#defaultSize">
                      		<i class="la la-plus-circle"></i> Thêm QRCode dự trữ
                      	</a>
                  	</div>
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>
                                <div class="form-group col-md-8">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-4">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <th>Thông tin</th>
                                                <th class="text-center">SL xuất</th>
                                                <th class="text-center">SL đã kiểm tra</th>
                                                <th class="text-center">Ngày tạo</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrBlocks->getAdapter()->count() > 0){
                                                $i = 1;
                                                foreach($this->arrBlocks as $item){
                                        ?>
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                                <td>
                                                	<?= '<span class="font-weight-bold">Tên:</span> ' . $item['name'] ?><br />
                                                	<?= '<span class="font-weight-bold">Số lượng serial:</span> ' . $item['number_serial'] ?><br />
                                                	<?= '<span class="font-weight-bold">QRCode:</span> ' . ($item['is_qrcode'] ? 'Có' : 'Không') ?>
                                                </td>
                                                <td class="text-center align-middle"><?= $item['number_created'] ?></td>
                                                <td class="text-center align-middle"><?= $item['number_checked'] ?></td>
                                                <td class="text-center align-middle"><?= $item['created_at']; ?></td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrBlocks,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'codes/index', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>





























<?php
?>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div id="pxtSearch" role="tablist" class="minimal-faq" aria-multiselectable="true">
                                    <div class="card m-b-0">
                                        <div class="card-header" role="tab" id="pxtHeading">
                                            <h5 class="mb-0">
                                          	</h5>
                                        </div>
                                        <div id="pxtCollapse" class="collapse <?= isset($this->queries['btnSubmit']) ? 'show' : '' ?>" role="tabpanel" aria-labelledby="pxtHeading">
                                            <div class="card-body">
                                                <?php
                                                    $this->formSearch->prepare();
                                                ?>
                                                <?= $this->form()->openTag($this->formSearch) ?>
                                                
                                                <div class="form-group col-md-6">
                                                    <?= $this->formElement($this->formSearch->get('keyword')) ?>
                                                    <div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <?php
                                                        echo $this->formRow($this->formSearch->get('btnSubmit'));
                                                    ?>
                                                </div>
                                                <?=$this->form()->closeTag($this->form)?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive m-t-10">
                                	
                                    <table class="display nowrap table table-hover table-striped" cellspacing="0" width="100%">
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                