<?php
$firstPage = 1;
$lastPage = ceil((int)$totalRow / (int)$perPage);
?>
<tfoot>
  <tr>
    <th colspan="3" class="align-middle">
      <div class="btn-group">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <?= $perPage ?> dòng
        </button>
        <div class="dropdown-menu">
          <?php
          $arrPerPage = explode(',', $contentPaginator['per_pages']);
          foreach ($arrPerPage as $key => $item) {
            $queries['per_page'] = $item;
          ?>
            <a class="dropdown-item" href="<?= $this->url($route, $params, ['query' => $queries]) ?>"><?= $item ?> dòng</a>
          <?php
          }
          ?>
        </div>
      </div>
      Hiển thị từ <?= ((int)((int)$perPage * ((int)$page - 1)) + 1) ?> đến <?= ((int)((int)$perPage * ((int)$page - 1)) + count($data)) ?> trong <?= $totalRow ?> dòng được tìm thấy
    </th>
    <th colspan="100" class="align-middle">
      <ul class="pagination justify-content-end">
        <?php
        if ((int)$page === $firstPage) {
        ?>
          <li class="page-item disabled">
            <span class="page-link">&laquo;</span>
          </li>
        <?php
        } else {
          $queries['page'] = (int)$page - 1;
          $queries['per_page'] = $perPage;
        ?>
          <li class="page-item">
            <a class="page-link" href="<?= $this->url($this->route, $params, ['query' => $queries]) ?>" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Trước</span>
            </a>
          </li>
        <?php
        }
        ?>
        <?php
        $pageRange = (int)$contentPaginator['page_range'];
        // Xác định trang hiển thị chạy từ đâu
        $beginPageRange = $page - ceil((int)$pageRange / 2);
        $endPageRange = $page + ceil((int)$pageRange / 2) - 1;
        if ($beginPageRange < $firstPage) {
          $beginPageRange = $firstPage;
          $endPageRange = $beginPageRange + $pageRange - 1;
          if ($endPageRange > $lastPage) {
            $endPageRange = $lastPage;
          }
        } elseif ($endPageRange > $lastPage) {
          $endPageRange = $lastPage;
          $beginPageRange = $endPageRange - $pageRange + 1;
          if ($beginPageRange < $firstPage) {
            $beginPageRange = $firstPage;
          }
        }
        for ($i = $beginPageRange; $i <= $endPageRange; $i++) {
          if ($i == $page) {
        ?>
            <li class="page-item active">
              <span class="page-link">
                <?= $i ?> <span class="sr-only">(current)</span>
              </span>
            </li>
          <?php
          } else {
            $queries['page'] = $i;
            $queries['per_page'] = $perPage;
          ?>
            <li class="page-item">
              <a class="page-link" href="<?= $this->url($this->route, $params, ['query' => $queries]) ?>">
                <?= $i ?> </a>
            </li>
        <?php
          }
        }
        ?>
        <?php
        if ((int)$page === $lastPage) {
        ?>
          <li class="page-item disabled">
            <span class="page-link">&raquo;</span>
          </li>
        <?php
        } else {
          $queries['page'] = (int)$page + 1;
          $queries['per_page'] = $perPage;
        ?>
          <li class="page-item">
            <a class="page-link" href="<?= $this->url($this->route, $params, ['query' => $queries]) ?>">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Sau</span>
            </a>
          </li>
        <?php
        }
        ?>
      </ul>
    </th>
  </tr>
</tfoot>