<?php 
    $query = $this->queries;
    $params = isset($this->param) ? $this->param : [];
?>
<?php if ($this->pageCount): ?><tfoot>
	<tr>
		<th colspan="3" class="align-middle">
			<div class="btn-group">
				<button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<?= $this->itemCountPerPage ?> dòng
				</button>
				<div class="dropdown-menu">
        			<?php 
        			    $arrPerPage = explode(',', $this->contentPaginator['per_pages']);
        			    foreach($arrPerPage as $key => $item){
        			        if($this->itemCountPerPage != $key){
        			            $query['per_page'] = $item;
        			?>
					<a class="dropdown-item" href="<?= $this->url($this->route, $params, ['query' => $query]) ?>"><?= $item ?> dòng</a>
        			<?php
        			        }
        			    }
        			?>
				</div>
			</div>
			Hiển thị từ <?= $this->firstItemNumber ?> đến <?= $this->lastItemNumber ?> trong <?= $this->totalItemCount ?> dòng được tìm thấy
		</th>
		<th colspan="100" class="align-middle">
  <ul class="pagination justify-content-end">
  <?php if (isset($this->previous)): ?>
    <li class="page-item">
      <a class="page-link" <?php $query['page'] = $this->previous; $query['per_page'] = $this->itemCountPerPage; ?>
      href="<?= $this->url($this->route, $params, ['query' => $query]) ?>" 
      aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
  <?php else: ?>
    <li class="page-item disabled">
        <span class="page-link">&laquo;</span>
    </li>
  <?php endif ?>
  
  
  <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page !== $this->current): ?>
      <li class="page-item">
        <a class="page-link" <?php $query['page'] = $page; $query['per_page'] = $this->itemCountPerPage; ?>
        href="<?= $this->url($this->route, $params, ['query' => $query]) ?>">
          <?= $page ?>
        </a>
      </li>
    <?php else: ?>
      <li class="page-item active">
          <span class="page-link">
            <?= $page ?>
            <span class="sr-only">(current)</span>
          </span>
      </li>
    <?php endif ?>
  <?php endforeach ?>

  <!-- Next page link -->
  <?php if (isset($this->next)): ?>
    <li class="page-item">
      <a class="page-link" <?php $query['page'] = $this->next; $query['per_page'] = $this->itemCountPerPage; ?>
      href="<?= $this->url($this->route, $params, ['query' => $query]) ?>">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  <?php else: ?>
    <li class="page-item disabled">
        <span class="page-link">&raquo;</span>
    </li>
  <?php endif ?>
  </ul>
		</th>
	</tr>
</tfoot>
<?php endif ?>
