<?php
    $title = "Thông tin cá nhân";
    $value = $this->valueCurrent;
    $optionPositions = $this->optionPositions;
?>
<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= TEMPS ?>app-assets/css/pages/users.min.css">
<div class="app-content container center-layout mt-2">
      <div class="content-wrapper">
        <div class="content-header row mb-1">
        </div>
        <div class="content-body">
            <div class="row match">
                <!-- <div class="col-xl-4 col-md-6 col-12">
                    <div class="card profile-card-with-cover border-success border-lighten-1">
                        <img class="card-img-top img-fluid bg-cover height-200 border-bottom-success border-custom-color" src="<?= ($value['background_avatar'] != '') ? URL_UPLOAD.$value['background_avatar'] : '/img/fortune.png' ?>"></img>
                        <div class="card-profile-image">
                            <img src="<?= ($value['avatar'] != null) ? URL_UPLOAD.$value['avatar'] : (($value['gender'] == 0) ? '/img/female-user.png' : '/img/male-user.png') ?>" 
                                class="rounded-circle width-150 height-150 img-border box-shadow-1" alt="Card image">
                        </div>
                        <div class="profile-card-with-cover-content text-center">
                            <div class="card-body">
                                <br>
                                <h4 style="font-size: 24px; font-family:Arial, Helvetica, sans-serif" class="card-title"><?= $value['name']?></h4>
                                
                                <h6 class="card-subtitle text-muted"><?= $value['email']?></h6><br>
                                <h6 class="card-subtitle text-muted"><?= ($value['position_id'] == null) ? "" : $optionPositions[$value['position_id']]?></h6>
                            </div>
                            <div class="text-center">
                                <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-facebook"><span class="la la-facebook"></span></a>
                                <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-twitter"><span class="la la-twitter"></span></a>
                                <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-linkedin"><span class="la la-skype font-medium-4"></span></a>
                                <a href="#" class="btn btn-social-icon mb-1 btn-outline-github"><span class="la la-youtube font-large-1"></span></a>
                            </div>
                        </div>
                    </div>
                </div> -->
                <div class="col-xl-3 col-md-6 col-12">
                    <div class="card">
                        <div class="text-center">
                            <div class="card-body">
                                <img src="<?= ($value['avatar'] != null) ? URL_UPLOAD.$value['avatar'] : (($value['gender'] == 0) ? '/img/female-user.png' : '/img/male-user.png') ?>" class="rounded-circle width-150 height-150" alt="Card image">
                            </div>
                            <div class="card-body">
                                <h4 class="card-title"><?= $value['name']?></h4>
                                <h6 class="card-subtitle text-muted"><?= $value['email']?></h6><br>
                                <h6 class="card-subtitle text-muted"><?= ($value['position_id'] == null) ? "" : $optionPositions[$value['position_id']]?></h6>
                            </div>
                            <div class="text-center">
                            <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-facebook"><span class="la la-facebook"></span></a>
                            <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-twitter"><span class="la la-twitter"></span></a>
                            <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-linkedin"><span class="la la-skype font-medium-4"></span></a>
                            <a href="#" class="btn btn-social-icon mb-1 btn-outline-github"><span class="la la-youtube font-large-1"></span></a>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-8 col-md-6 col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" style="font-size: 20px;"><?= $title?></h4>
                            <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body">
                                <?php $this->form->prepare(); ?>
                                <?= $this->form()->openTag($this->form) ?>
                                <div class="form-group col-md-6 ">
                                    <?= $this->formLabel($this->form->get('firstname')) ?>
                                    <?= $this->formElement($this->form->get('firstname')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('firstname')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('lastname')) ?>
                                    <?= $this->formElement($this->form->get('lastname')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('lastname')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('birthday')) ?>
                                    <?= $this->formElement($this->form->get('birthday')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('birthday')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('home_town')) ?>
                                    <?= $this->formElement($this->form->get('home_town')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('home_town')) ?></div>
                                </div>
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('addresses')) ?>
                                    <?= $this->formElement($this->form->get('addresses')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('addresses')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('phones')) ?>
                                    <?= $this->formElement($this->form->get('phones')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('phones')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('identity_cards')) ?>
                                    <?= $this->formElement($this->form->get('identity_cards')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('identity_cards')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('email')) ?>
                                    <?= $this->formElement($this->form->get('email')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('email')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('position_id')) ?>
                                    <?= $this->formElement($this->form->get('position_id')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('position_id')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('level_educations')) ?>
                                    <?= $this->formElement($this->form->get('level_educations')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('level_educations')) ?></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('gender')) ?>
                                    <?= $this->formElement($this->form->get('gender')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('gender')) ?></div>
                                </div>
                                
                                <?=$this->form()->closeTag($this->form)?>
                            </div>
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
// $(function () {
// 	$(':radio:not(:checked)').attr('disabled', true);
// });
</script>









<!-- <link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= TEMPS ?>app-assets/css/pages/users.min.css">
<div class="app-content container center-layout mt-2">
      <div class="content-wrapper">
        <div class="content-header row mb-1">
        </div>
        <div class="content-body">
            <div class="row match">
                <div class="col-xl-4 col-md-6 col-12">
                    <div class="card profile-card-with-cover border-success border-lighten-1">
                        <img class="card-img-top img-fluid bg-cover height-200 border-success border-lighten-1" src="<?= ($value['background_avatar'] != '') ? URL_UPLOAD.$value['background_avatar'] : '/img/fortune.png'?>"></img>
                        <div class="card-profile-image">
                            <img src="<?= ($value['avatar'] != null) ? URL_UPLOAD.$value['avatar'] : (($value['gender'] == 0) ? '/img/female-user.png' : '/img/male-user.png') ?>" class="rounded-circle img-border box-shadow-1" alt="Card image">
                        </div>
                        <div class="profile-card-with-cover-content text-center">
                            <div class="card-body">
                                <h4 style="font-size: 24px; font-family:Arial, Helvetica, sans-serif" class="card-title"><?= $value['name']?></h4>
                                <ul class="list-inline list-inline-pipe">
                                    <li><?= $value['email']?></li>
                                </ul>
                                <h6 class="card-subtitle text-muted"><?= $value['positions']?></h6>
                            </div>
                            <div class="text-center">
                                <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-facebook"><span class="la la-facebook"></span></a>
                                <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-twitter"><span class="la la-twitter"></span></a>
                                <a href="#" class="btn btn-social-icon mr-1 mb-1 btn-outline-linkedin"><span class="la la-skype font-medium-4"></span></a>
                                <a href="#" class="btn btn-social-icon mb-1 btn-outline-github"><span class="la la-youtube font-large-1"></span></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-8 col-md-6 col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" style="font-size: 20px;"><?= $title?></h4>
                            <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body">
                                <form class="form-horizontal row">
                                    <div class="form-group col-md-6 ">
                                        <label for="firstname">Họ và tên đệm:</label>
                                        <input type="text" class="form-control" value="<?= $value['firstname']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Tên:</label>
                                        <input type="text" class="form-control" value="<?= $value['lastname']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Ngày tháng năm sinh:</label>
                                        <input type="text" class="form-control" value="<?= $value['birthday']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Quê quán:</label>
                                        <input type="text" class="form-control" value="<?= $value['home_town']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Địa chỉ:</label>
                                        <input type="text" class="form-control" value="<?= $value['addresses']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Số điện thoại:</label>
                                        <input type="text" class="form-control" value="<?= $value['phones']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">CCCD / CMND:</label>
                                        <input type="text" class="form-control" value="<?= $value['identity_cards']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Email:</label>
                                        <input type="text" class="form-control" value="<?= $value['email']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Chức vụ:</label>
                                        <input type="text" class="form-control" value="<?= $value['positions']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Trình độ học vấn:</label>
                                        <input type="text" class="form-control" value="<?= $value['level_educations']?>" readonly>
                                    </div>
                                    <div class="form-group col-md-6 ">
                                        <label for="lastname">Giới tính:</label>
                                        <input type="text" class="form-control" value="<?= ($value['gender'] == 0) ? "Nữ" : "Nam" ?>" readonly>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div> -->
<!-- <script type="text/javascript" src="<?= TEMPS ?>assets/moment.js/2.22.2/moment-with-locales.min.js"></script>
<script type="text/javascript" src="<?= TEMPS ?>assets/moment-timezone/0.5.21/moment-timezone-with-data-2012-2022.min.js"></script>
<script src="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/js/tempusdominus-bootstrap-4.js"></script>
<script type="text/javascript">
$(function () {
	$('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss'
   	});
});
</script> -->