<?php
$title = "Quản lý công ty";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                  	<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tính năng</button>
                  	<div class="dropdown-menu arrow">
                      	<a class="dropdown-item pxt-modal" href="javascript:void(0)" title="Thêm dữ liệu" 
                      		route="<?= $this->url('settings/companies', ['action' => 'add']) ?>" data-toggle="modal" data-target="#xlarge">
                      		<i class="la la-plus-circle"></i> Thêm dữ liệu
                      	</a>
                  	</div>
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>
                                <div class="form-group col-md-8">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-4">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <th class="text-center">Mã công ty</th>
                                                <th class="text-center">Tên công ty</th>
                                                <th class="text-center">Mã số thuế</th>
                                                <th class="text-center">Địa chỉ</th>
                                                <th class="text-center">Điện thoại</th>
                                                <th class="text-center">Ngày tạo</th>
                                                <?php if(isset($this->userId) && $this->userId == '1'){?>
                                                    <th class="text-center">Tài khoản</th>
                                                    <th class="text-center">Thông tin bổ sung</th>
                                                <?php } ?>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrCompanies->getAdapter()->count() > 0){
                                                $i = 1;
                                                $optionUsernames = $this->optionUsernames;
                                                foreach($this->arrCompanies as $item){
                                        ?>
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                            	<td class="align-middle"><?= $item['id'] ?></td>
                                            	<td class="align-middle"><?= $item['name'] ?></td>
                                                <td class="align-middle"><?= $item['tax_code'] ?></td>
                                                <td class="text-center align-middle"><?= $item['full_address']; ?></td>
                                                <td class="text-center align-middle"><?= $item['phone']; ?></td>
                                                <td class="text-center align-middle"><?= $item['created_at']; ?></td>
                                                <?php if(isset($this->userId) && $this->userId == '1'){?>
                                                    <td class="align-middle"><?=  (($item['user_id']!= null ) ? $optionUsernames[$item['user_id']] : '' )?></td>
                                                    <td class="text-center align-middle">
                                                    <div class="btn-group">
                                                      	<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tính năng</button>
                                                      	<div class="dropdown-menu arrow">
                                                          	<a class="dropdown-item pxt-modal" href="javascript:void(0)" title="Cấu hình phân trang <?= $item['id'] ?>" 
                                                          		route="<?= $this->url('settings/company-configs', ['action' => 'paginators', 'id' => $item['id']]) ?>" data-toggle="modal" data-target="#defaultSize">
                                                          		Cấu hình phân trang
                                                          	</a>
                                                          	<a class="dropdown-item pxt-modal" href="javascript:void(0)" title="Cấu hình tin nhắn trả ra <?= $item['id'] ?>" 
                                                          		route="<?= $this->url('settings/company-configs', ['action' => 'messages', 'id' => $item['id']]) ?>" data-toggle="modal" data-target="#xlarge">
                                                          		Cấu hình tin nhắn trả ra
                                                          	</a>
                                                          	<a class="dropdown-item pxt-modal" href="javascript:void(0)" title="Cấu hình giao diện <?= $item['id'] ?>" 
                                                          		route="<?= $this->url('settings/company-configs', ['action' => 'displays', 'id' => $item['id']]) ?>" data-toggle="modal" data-target="#defaultSize">
                                                          		Cấu hình giao diện
                                                          	</a>
                                                          	<a class="dropdown-item pxt-modal" href="javascript:void(0)" title="Cấu hình vật tư <?= $item['id'] ?>" 
                                                          		route="<?= $this->url('settings/company-configs', ['action' => 'supplies', 'id' => $item['id']]) ?>" data-toggle="modal" data-target="#defaultSize">
                                                          		Cấu hình vật tư
                                                          	</a>
                                                            <a class="dropdown-item pxt-modal" title="Cấu hình form sản phẩm <?= $item['id'] ?>" href="javascript:void(0)" data-toggle="modal" data-target="#xlarge"
                                                            	route="<?= $this->url('settings/company-configs', ['action' => 'form-products-iframe', 'id' => $item['id']]) ?>">
                                                            	Cấu hình form sản phẩm
                                                            </a>
                                                            <a class="dropdown-item pxt-modal" title="Cấu hình form đại lý <?= $item['id'] ?>" href="javascript:void(0)" data-toggle="modal" data-target="#xlarge"
                                                            	route="<?= $this->url('settings/company-configs', ['action' => 'form-agents-iframe', 'id' => $item['id']]) ?>">
                                                            	Cấu hình form đại lý
                                                            </a>
                                                            <a class="dropdown-item pxt-modal" title="Cấu hình quản lý cột sản phẩm <?= $item['id'] ?>" href="javascript:void(0)" data-toggle="modal" data-target="#xlarge"
                                                            	route="<?= $this->url('settings/company-configs', ['action' => 'manage-products-iframe', 'id' => $item['id']]) ?>">
                                                            	Cấu hình quản lý cột sản phẩm
                                                            </a>
                                                            <a class="dropdown-item pxt-modal" title="Cấu hình quản lý cột đại lý <?= $item['id'] ?>" href="javascript:void(0)" data-toggle="modal" data-target="#xlarge"
                                                            	route="<?= $this->url('settings/company-configs', ['action' => 'manage-agents-iframe', 'id' => $item['id']]) ?>">
                                                            	Cấu hình quản lý cột đại lý
                                                            </a>
                                                            <a class="dropdown-item pxt-modal" title="Cấu hình sản phẩm mặc định <?= $item['id'] ?>" href="javascript:void(0)" data-toggle="modal" data-target="#xlarge"
                                                            	route="<?= $this->url('settings/company-configs', ['action' => 'config-codes-iframe', 'id' => $item['id']]) ?>">
                                                            	Cấu hình sản phẩm mặc định
                                                            </a>
                                                            <a class="dropdown-item pxt-modal" title="Cấu hình layout <?= $item['id'] ?>" href="javascript:void(0)" data-toggle="modal" data-target="#xlarge"
                                                            	route="<?= $this->url('settings/company-configs', ['action' => 'layouts-iframe', 'id' => $item['id']]) ?>">
                                                            	Cấu hình layout 
                                                            </a>
                                                      	</div>
                                                    </div>
                                                </td>
                                                <?php } ?>
                                                
                                                <td class="text-center align-middle">
                                                    <a title="Sửa dữ liệu" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                    	route="<?= $this->url('settings/companies', ['action' => 'edit', 'id' => $item['id']]) ?>">
    													<i class="la la-pencil"></i></a>
                                                    <a title="Địa chỉ" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                        route="<?= $this->url('settings/companies', ['action' => 'iframe-address', 'id' => $item['id']]) ?>">
                                                        <i class="la la-map-marker"></i></a>
                                                    <a title="Người đại diện" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                        route="<?= $this->url('settings/companies', ['action' => 'iframe-surrogate', 'id' => $item['id']]) ?>">
                                                        <i class="la la-user-plus"></i></a>
                                                    <a title="Bạn muốn xóa '<?= $item['name']; ?>'?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('settings/companies', ['action' => 'delete', 'id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrCompanies,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'settings/companies', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
