<?php
$title = "Chi tiết hóa đơn";
$this->headTitle($title);

?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
                    <div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Reset mã</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->form->prepare(); ?>
                             	<?= $this->form()->openTag($this->form) ?>
                             	
                                <div class="form-group col-md-3">
                             		<?= $this->formElement($this->form->get('codes')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('codes')) ?></div>
                              	</div>
							
                             	<div class="form-group col-md-1 text-center">
                                	<?= $this->formRow($this->form->get('btnSubmit')) ?>
                             	</div>
                             	
                            	<?=$this->form()->closeTag($this->form)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                            	<th class="text-center">STT</th>
                                            	<th class="text-center">Sản Phẩm</th>
                                            	<th class="text-center">Số lượng</th>
                                            	<th class="text-center">Đơn giá</th>
                                            	<th class="text-center">Thành tiền</th>
                                                <th class="text-center">Serial</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if(count($this->arrDetails) > 0){
                                                $optionProducts = $this->optionProducts;
                                                //$optionProductsDetail = $this->optionProductsDetail;
                                                $i = 1;
                                                $a = 0;
                                                foreach($this->arrDetails as $item){
                                        ?>
                                            <tr>
                                            	<td class="text-center"><?= $i ?></td>
                                            	<td class="text-center"><?= isset($optionProducts[$item['product_id']]) ? $optionProducts[$item['product_id']] : "" ?></td>
                                            	<td class="text-center"><?= $item['quantity']?></td>
                                            	<td class="text-center"><?= $item['unit_price'] ?></td>
                                            	<td class="text-center"><?= $item['total_price'] ?></td>
                                                <td class="text-center"><?= $item['code_serial'] ?></td>
                                            </tr>
                                        <?php
                                                    $i++;
                                                    $a += $item['total_price'];
                                                }
                                                ?>
                                                <tr>
                                                    <th colspan="100" class="text-center">Tổng cộng: <?= $a?></th>
                                                </tr>
                                        <?php
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Chưa có dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>