<?php
$title = "Cấu hình tin nhắn trả ra (mặc định)";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                				<?= $this->partial("settings/index/nav-tabs.phtml", ['route' => 'settings/index', 'id' => 'messages-default']) ?>
                               	<div class="tab-content">
                                   	<div class="tab-pane active" id="messages" role="tabpanel">
                                     	<div class="p-20">
                                     		<?php $this->form->prepare(); ?>
                                     		<?= $this->form()->openTag($this->form) ?>
                                            <div class="form-group col-md-12 text-center">
                                            	<h1>Tin nhắn cho người tiêu dùng</h1>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_success')) ?>
                                                <?= $this->formElement($this->form->get('message_success')) ?>
                                                <small class="font-italic">Các tham số có thể cấu hình thêm: 
                                                [tin_nhan_den] - Tin nhắn mà khách hàng nhắn tin đến; 
                                                [ma_pin] - Mã pin đúng; 
                                                [ngay] - Ngày nhắn; 
                                                [ngay_gio] - Ngày giờ nhắn; 
                                                [so_dien_thoai] - Số điện thoại;</small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_success')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_invalid')) ?>
                                                <?= $this->formElement($this->form->get('message_invalid')) ?>
                                                <small class="font-italic">Các tham số có thể cấu hình thêm: 
                                                [tin_nhan_den] - Tin nhắn mà khách hàng nhắn tin đến; 
                                                [ngay] - Ngày nhắn; 
                                                [ngay_gio] - Ngày giờ nhắn; 
                                                [so_dien_thoai] - Số điện thoại;</small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_invalid')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_checked')) ?>
                                                <?= $this->formElement($this->form->get('message_checked')) ?>
                                                <small class="font-italic">Các tham số có thể cấu hình thêm: 
                                                [tin_nhan_den] - Tin nhắn mà khách hàng nhắn tin đến; 
                                                [ma_pin] - Mã pin đúng; 
                                                [ngay] - Ngày nhắn; 
                                                [ngay_gio] - Ngày giờ nhắn;
                                                [tu_ngay] - Ngày nhắn; 
                                                [tu_ngay_gio] - Ngày giờ nhắn;
                                                [so_dien_thoai] - Số điện thoại;
                                                [so_dien_thoai_da_nhan] - Số điện thoại đã kiểm tra trước đó;</small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_checked')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_outdate')) ?>
                                                <?= $this->formElement($this->form->get('message_outdate')) ?>
                                                <small class="font-italic">Các tham số có thể cấu hình thêm: 
                                                [tin_nhan_den] - Tin nhắn mà khách hàng nhắn tin đến; 
                                                [ma_pin] - Mã pin đúng; 
                                                [ngay] - Ngày nhắn; 
                                                [ngay_gio] - Ngày giờ nhắn;
                                                [so_dien_thoai] - Số điện thoại;</small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_outdate')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12 text-center">
                                            	<h1>Tin nhắn cho đại lý</h1>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_success_agent')) ?>
                                                <?= $this->formElement($this->form->get('message_success_agent')) ?>
                                                <small class="font-italic">Các tham số có thể cấu hình thêm: 
                                                [tin_nhan_den] - Tin nhắn mà khách hàng nhắn tin đến; 
                                                [ma_pin] - Mã pin đúng; 
                                                [ngay] - Ngày nhắn; 
                                                [ngay_gio] - Ngày giờ nhắn; 
                                                [so_dien_thoai] - Số điện thoại;</small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_success_agent')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_invalid_agent')) ?>
                                                <?= $this->formElement($this->form->get('message_invalid_agent')) ?>
                                                <small class="font-italic">Các tham số có thể cấu hình thêm: 
                                                [tin_nhan_den] - Tin nhắn mà khách hàng nhắn tin đến; 
                                                [ngay] - Ngày nhắn; 
                                                [ngay_gio] - Ngày giờ nhắn; 
                                                [so_dien_thoai] - Số điện thoại;</small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_invalid_agent')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_checked_agent')) ?>
                                                <?= $this->formElement($this->form->get('message_checked_agent')) ?>
                                                <small class="font-italic">Các tham số có thể cấu hình thêm: 
                                                [tin_nhan_den] - Tin nhắn mà khách hàng nhắn tin đến; 
                                                [ma_pin] - Mã pin đúng; 
                                                [ngay] - Ngày nhắn; 
                                                [ngay_gio] - Ngày giờ nhắn;
                                                [tu_ngay] - Ngày nhắn; 
                                                [tu_ngay_gio] - Ngày giờ nhắn;
                                                [so_dien_thoai] - Số điện thoại;
                                                [so_dien_thoai_da_nhan] - Số điện thoại đã kiểm tra trước đó;</small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_checked_agent')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <?= $this->formLabel($this->form->get('message_outdate_agent')) ?>
                                                <?= $this->formElement($this->form->get('message_outdate_agent')) ?>
                                                <small class="font-italic">Các tham số có thể cấu hình thêm: 
                                                [tin_nhan_den] - Tin nhắn mà khách hàng nhắn tin đến; 
                                                [ma_pin] - Mã pin đúng; 
                                                [ngay] - Ngày nhắn; 
                                                [ngay_gio] - Ngày giờ nhắn;
                                                [so_dien_thoai] - Số điện thoại;</small>
                                                <div class="text-danger"><?= $this->formElementErrors($this->form->get('message_outdate_agent')) ?></div>
                                            </div>
                                            <div class="form-group col-md-12 text-center">
                                                <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                            </div>
                                            <?= $this->form()->closeTag($this->form) ?>
                                     	</div>
                                  	</div>
                             	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>