<?php include_once( APPLICATION_PATH . "/module/Admin/view/layout/layout-admin/script-notification.php"); ?>
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow navbar-static-top navbar-light navbar-brand-center">
  <div class="navbar-wrapper">
    <div class="navbar-header">
      <ul class="nav navbar-nav flex-row">
        <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
        <li class="nav-item"><a class="navbar-brand" href="<?= $this->url('admin/index', ['action' => 'index']) ?>" style="padding: 5px 0;">
          <img style="width: 100%;" class="brand-logo" alt="modern admin logo" src="<?= TEMPS ?>app-assets/images/logo/logo.jpg"></a></li>
        <li class="nav-item d-md-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a></li>
      </ul>
    </div>
    <div class="navbar-container content">
      <div class="collapse navbar-collapse" id="navbar-mobile">
        <ul class="nav navbar-nav mr-auto float-left">
          <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu"></i></a></li>
          <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>
        </ul>
        <ul class="nav navbar-nav float-right">
          <?php if(\Admin\Service\Authentication::getCompanyId() == null || \Admin\Service\Authentication::getCompanyId() ==''){ ?>
            <li  class="dropdown dropdown-notification nav-item">
              <a class="nav-link nav-link-label" href="#" data-toggle="dropdown"><i class="ficon ft-bell"></i>
                  <span id="header-count-notify" class="badge badge-pill badge-danger badge-up badge-glow"></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                  <li class="dropdown-menu-header">
                      <h6 class="dropdown-header m-0"><span class="grey darken-2">Thông báo</span></h6>
                      <div id="mark-as-read" style="cursor: pointer;">
                        <span class="notification-tag badge btn-outline-primary float-right m-0"><b>Đánh dấu tất cả đã đọc</b></span>
                      </div>
                  </li>
                  <li id="nav-bar-notify" class="scrollable-container media-list w-100">
                    
                  </li>
                  <li class="dropdown-menu-footer">
                      <p id="read-more" class="dropdown-item text-muted text-center" style="cursor: pointer;padding: 0.3rem;margin-bottom: -20px;border-top: 1px solid #E4E5EC;">Xem thêm thông báo</p>
                  </li>
              </ul>
            </li>
          <?php } ?>
          <li class="dropdown dropdown-user nav-item">
            <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
              <span class="mr-1 user-name text-bold-700"><?= $this->sessionContainer->lastname . ' ' . $this->sessionContainer->firstname ?></span>
              <span class="avatar avatar-online"><img src="<?= ($this->sessionContainer->gender == 0) ? ('/img/female-user.png') : ('/img/male-user.png') ?>" alt="user" class="profile-pic" /><i></i></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <?php if(\Admin\Service\Authentication::getCompanyId() != null || \Admin\Service\Authentication::getCompanyId() !=''){ ?>
                <a class="dropdown-item" href="<?= $this->url('admin/users', ['action' => 'profile']) ?>"><i class="ft-user"></i> Sửa thông tin</a>
              <?php }else{ ?>
                <a class="dropdown-item" href="<?= $this->url('persons/profiles', ['action' => 'edit']) ?>"><i class="ft-user"></i> Sửa thông tin</a>
              <?php } ?>
              
              <a class="dropdown-item" href="<?= $this->url('settings/index', ['action' => 'messages']) ?>"><i class="ft-settings"></i> Cấu hình chung</a>
              <a class="dropdown-item" href="<?= $this->url('supplies/proposals', ['action' => 'index']) ?>"><i class="ft-sun"></i> Đề xuất vật tư</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<?=$this->url('admin/index', ['action' => 'logout'])?>"><i class="ft-power"></i> Đăng xuất</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<!-- <script type="text/javascript"> 
var page = 1;
var route = "<?= $this->url("persons/notifications", ["action" => "index"]) ?>";
  function notification(page, route){
    $.ajax({
      method: 'post',
      url: route,
      data: {page: page},
      success: function(result){
        $("#nav-bar-notify").append(result)
      }
    })
  }
  $(function(){
    $.ajax({
      method: 'post',
      url: "<?= $this->url("persons/notifications", ["action" => "notify-unread"]) ?>",
      success: function(result){
        $("#header-count-notify").text(result);
      }
    });

    notification(page, route);
    
    $("#read-more").on("click",function(){
        page++;
        notification(page, route);
    });

    $("#mark-as-read").on("click", function(){
        var notifyId = [];
        $("#nav-bar-notify").find("div.not-read").each(function(index, notify){
          notifyId.push($(notify).data("nid"));
        });
        if(notifyId.length === 0){
          $.toast({
                heading: 'Cảnh báo',
                text: 'Bạn đã đọc hết thông báo.',
                position: 'top-right',
                loaderBg:'#ff6849',
                icon: 'warning',
                hideAfter: 3000, 
                stack: 6
              });
          return false
        }
        
        $.ajax({
          url: "<?= $this->url("persons/notifications", ["action" => "mark-read"]) ?>",
          type: "post",
          data: {notifyId: notifyId},
          success: function(result){
            // console.log(result)
            $("#nav-bar-notify").prepend(result)
            if(result == 'success'){
              notifyId.forEach(function(nid){
                $("#nav-bar-notify").find(`div[data-nid= ${nid}]`).removeClass("bg-blue-grey not-read");
              });
              var currentNotify =  +$("#header-count-notify").text()
              currentNotify -= notifyId.length;
              if(currentNotify === 0){
                  $("#header-count-notify").text("");
              }else{
                  $("#header-count-notify").text(currentNotify);
              }
            }
          }
        })
        return false;
    });
  })
</script> -->