<?php
$title = "Quản lý vật tư vào kho";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                  	<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tính năng</button>
                  	<div class="dropdown-menu arrow">
                      	<a class="dropdown-item pxt-modal" title="Thêm dữ liệu" href="<?= $this->url($this->route, ['action' => 'add', 'id' => $this->storehouseId]) ?>">
                      		<i class="la la-plus-circle"></i> Thêm dữ liệu
                      	</a>
                  	</div>
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                            	<th class="text-center">STT</th>
                                            	<th class="text-center">Vật tư</th>
                                            	<th class="text-center">Nhà cung cấp</th>
                                            	<th class="text-center">Số lượng</th>
                                                <th class="text-center">Ngày tạo</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrSuppliesIns->getAdapter()->count() > 0){
                                                $i = 1;
                                                $optionSupplies = $this->optionSupplies;
                                                $optionSuppliers = $this->optionSuppliers;
                                                $contentSupplies = isset($this->contentSupplies) ? $this->contentSupplies : 0;
                                                $timeCurrent = strtotime( \Pxt\Datetime\ChangeDatetime::getDatetimeCurrent() );
                                                foreach($this->arrSuppliesIns as $item){
                                        ?>
                                            <tr>
                                            	<td class="align-middle text-center"><?= $i++ ?></td>
                                            	<td class="align-middle text-center"><?= isset($optionSupplies[$item['supply_id']]) ? $optionSupplies[$item['supply_id']] : "Không xác định" ?></td>
                                            	<td class="align-middle text-center"><?= isset($optionSuppliers[$item['supplier_id']]) ? $optionSuppliers[$item['supplier_id']] : "Không xác định" ?></td>
                                            	<td class="align-middle text-center"><?= $item['number'] ?></td>
                                                <td class="align-middle text-center"><?= date_format(date_create($item['created_at']), 'd/m/Y H:i:s') ?></td>
                                                <td class="align-middle text-center">
                                                	<?php 
                                                	   if(isset($contentSupplies['time_limit_supplies_ins'])){
                                                	       $timeFinish = (int)$contentSupplies['time_limit_supplies_ins'] + strtotime($item['created_at']);
                                                	       $timeRemain = $timeFinish - $timeCurrent;
                                                	       if((int)$contentSupplies['time_limit_supplies_ins'] < 0 || $timeRemain > 0){
                                                	?>
                                                    <a title="Sửa dữ liệu" href="<?= $this->url('supplies/supplies-ins', ['action' => 'edit', 'id' => $this->storehouseId, 'supplies_in_id' => $item['id']]) ?>">
    													<i class="la la-pencil"></i></a>
                                                    <a title="Bạn muốn xóa dữ liệu này?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('supplies/supplies-ins', ['action' => 'delete', 'id' => $this->storehouseId, 'supplies_in_id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
    												<?php 
                                                    	   }
                                                        }
    												?>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>