<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= TEMPS ?>app-assets/vendors/css/forms/selects/select2.min.css">
<?php
$title = "Thêm KPI";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'index']) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                        		<?php $this->form->prepare(); ?>
                                <?= $this->form()->openTag($this->form) ?>
                                <div class="form-horizontal row">
                                    <div class="form-group col-md-4">
                                        <?= $this->formLabel($this->form->get('year')) ?>
                                        <?= $this->formElement($this->form->get('year')) ?>
                                        <div class="text-danger"><?= $this->formElementErrors($this->form->get('year')) ?></div>
                                    </div><br>
                                </div>
                                
                                <div data-repeater-list="data_repeater">
                                    <div data-repeater-item class="form-horizontal row">
                                        <div class="form-group col-md-6">
                                            <?= $this->formLabel($this->form->get('target')) ?>
                                            <?= $this->formElement($this->form->get('target')) ?>
                                            <div class="text-danger"><?= $this->formElementErrors($this->form->get('target')) ?></div>
                                        </div>
                                        
                                        <div class="form-group col-md-6">
                                            <?= $this->formLabel($this->form->get('measure')) ?>
                                            <?= $this->formElement($this->form->get('measure')) ?>
                                            <div class="text-danger"><?= $this->formElementErrors($this->form->get('measure')) ?></div>
                                        </div>
                                        
                                        <div class="form-group col-md-6">
                                            <?= $this->formLabel($this->form->get('expected_results')) ?>
                                            <?= $this->formElement($this->form->get('expected_results')) ?>
                                            <div class="text-danger"><?= $this->formElementErrors($this->form->get('expected_results')) ?></div>
                                        </div>
                                        
                                        <div class="form-group col-md-6">
                                            <?= $this->formLabel($this->form->get('action_program')) ?>
                                            <?= $this->formElement($this->form->get('action_program')) ?>
                                            <div class="text-danger"><?= $this->formElementErrors($this->form->get('action_program')) ?></div>
                                        </div>

                                        <!-- <div class="form-group col-md-12">
                                            <?//= $this->formLabel($this->form->get('results')) ?>
                                            <?//= $this->formElement($this->form->get('results')) ?>
                                            <div class="text-danger"><?//= $this->formElementErrors($this->form->get('results')) ?></div>
                                        </div> -->
                                        
                                        <div class="form-group col-md-12 text-center">
                                            <span type="button" class="btn btn-danger" data-repeater-delete> <i class="ft-x"></i>Delete</span>
                                        </div>
                                        <hr  class="col-md-11">
                                    </div>
                                </div>

                                <div class="form-group col-md-12 text-center">
                                    <span type="button" data-repeater-create class="btn btn-primary"><i class="ft-plus"></i>Thêm</span>&emsp;
                                    <?php
                                        echo $this->formRow($this->form->get('btnSubmit'));
                                    ?>
                                </div>
                                
                                <?=$this->form()->closeTag($this->form)?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<script src="<?= TEMPS ?>app-assets/vendors/js/forms/repeater/jquery.repeater.min.js"></script>
<script src="<?= TEMPS ?>app-assets/js/scripts/forms/form-repeater.min.js"></script>

<script type="text/javascript">
$(function () {
	$('.datetimepicker-input').datetimepicker({
        view: 'years',
       	format: 'YYYY'
   	});
});
</script>
