        <?php 
            $this->form->prepare();
            $this->form()->addValidAttribute('route');
        ?>
        <?= $this->form()->openTag($this->form) ?>
        
        <div class="form-group col-md-12 text-center">
            <a href="<?= $this->url('storehouses/agents', ['action' => 'add-excel-sample']) ?>">File mẫu</a>
        </div>
        
        <div class="form-group col-md-12 text-center">
            <?= $this->formLabel($this->form->get('file')) ?>
            <?= $this->formElement($this->form->get('file')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('file')) ?></div>
        </div>
        
        <div class="form-group col-md-12 text-center">
    		<button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    		<?= $this->formRow($this->form->get('btnSubmit')) ?>
		</div>
        <?=$this->form()->closeTag($this->form)?>
