<?php include_once( APPLICATION_PATH . "/module/Admin/view/layout/layout-admin/script-address.php"); ?>
        <?php 
            $this->form->prepare();
            $this->form()->addValidAttribute('route');
        ?>
        <?= $this->form()->openTag($this->form) ?>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('name')) ?>
            <?= $this->formElement($this->form->get('name')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('name')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('code')) ?>
            <?= $this->formElement($this->form->get('code')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('code')) ?></div>
        </div>

        <?php 
            if(!empty($settingDatas)){
                foreach($settingDatas as $key => $item){
        ?>
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get($key)) ?>
            <?= $this->formElement($this->form->get($key)) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get($key)) ?></div>
        </div>
        <?php 
                }
            }
        ?>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('address')) ?>
            <?= $this->formElement($this->form->get('address')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('address')) ?></div>
        </div>
        
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('status')) ?>
            <div class="demo-radio-button">
            <?= $this->formElement($this->form->get('status')) ?>
            </div>
        </div>
        
        <div class="form-group col-md-12 text-center">
    		<button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    		<?= $this->formRow($this->form->get('btnSubmit')) ?>
		</div>
        <?=$this->form()->closeTag($this->form)?>

<script src="<?= TEMPS ?>assets/ckeditor/full/ckeditor.js"></script>
<script src="<?= TEMPS ?>assets/ckfinder/ckfinder.js"></script>
<script>
<?php 
if(!empty($settingDatas)){
    foreach($settingDatas as $key => $item){
        if($item['type'] == "Textarea"){
            echo "CKEDITOR.replace( '" . $key . "' );";
        }
    }
}
?>
</script>