<?php include_once( APPLICATION_PATH . "/module/Admin/view/layout/layout-admin/script-address.php"); ?>
        <?php 
            $this->form->prepare();
            $this->form()->addValidAttribute('route');
        ?>
        <?= $this->form()->openTag($this->form) ?>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('name')) ?>
            <?= $this->formElement($this->form->get('name')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('name')) ?></div>
        </div>

        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('description')) ?>
            <?= $this->formElement($this->form->get('description')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('description')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('status')) ?>
            <div class="demo-radio-button">
            <?= $this->formElement($this->form->get('status')) ?>
            </div>
        </div>
        <div class="form-group col-md-12 text-center">
    		<button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    		<?= $this->formRow($this->form->get('btnSubmit')) ?>
		</div>
        <?=$this->form()->closeTag($this->form)?>
