<?php
$title = "Quản lý chương trình quay số";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                  	<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tính năng</button>
                  	<div class="dropdown-menu arrow">
                      	<a class="dropdown-item pxt-modal" title="Thêm dữ liệu" href="<?= $this->url($this->route, ['action' => 'add']) ?>">
                      		<i class="la la-plus-circle"></i> Thêm dữ liệu
                      	</a>
                  	</div>
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>
                                <?php if(isset($this->userId) && $this->userId == '1'){ ?>
                                <div class="form-group col-md-4">
                                    <?= $this->formElement($this->formSearch->get('company_id')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('company_id')) ?></div>
                                </div>
                                <?php } ?>
                                <div class="form-group col-md-4">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-4">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                            	<th class="text-center">STT</th>
                                                <?php if($this->userId == "1"){ ?><th class="text-center">Công ty</th><?php } ?>
                                                <th>Tên</th>
                                                <th class="text-center">Thời gian bắt đầu</th>
                                                <th class="text-center">Thời gian kết thúc</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrDials->getAdapter()->count() > 0){
                                                $i = 1;
                                                $optionCompanies = $this->optionCompanies;
                                                foreach($this->arrDials as $item){
                                        ?>
                                            <tr>
                                            	<td class="align-middle text-center"><?= $i++ ?></td>
                                            	<?php if($this->userId == "1"){ ?><td class="align-middle"><?= isset($optionCompanies[$item['company_id']]) ? $optionCompanies[$item['company_id']] : "Không xác định"; ?></td><?php } ?>
                                                <td class="align-middle"><?= $item['name']; ?></td>
                                                <td class="align-middle text-center">
                                                    <strong><?= date_format(date_create($item['datetime_begin']), 'd/m/Y H:i:s') ?></strong>
                                                </td>
                                                <td class="align-middle text-center">
                                                    <strong><?= date_format(date_create($item['datetime_end']), 'd/m/Y H:i:s') ?></strong>
                                                </td>
                                                <td class="align-middle text-center">
                                                    <a title="Sửa dữ liệu" href="<?= $this->url('promotions/dials', ['action' => 'edit', 'id' => $item['id']]) ?>">
    													<i class="la la-pencil"></i></a>
                                                    <a title="Bạn muốn xóa chương trình quay số '<?= $item['name']; ?>'?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('promotions/dials', ['action' => 'delete', 'id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
                                                    <a title="Quay số" class="pxt-dial" href="<?= $this->url('promotions/dials', ['action' => 'play', 'id' => $item['id']]) ?>">
    													<i class="la la-play"></i></a>
                                                    <a title="Nhập danh sách giải thưởng '<?= $item['name']; ?>'?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                    	route="<?= $this->url('promotions/dials', ['action' => 'iframe', 'id' => $item['id']]) ?>">
    													<i class="la la-list-alt"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrDials,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'promotions/dials', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<script type="text/javascript">
	var height = $(window).height(); // New height
	var width = $(window).width(); // New width
	$(function() {
		$(".pxt-dial").click(function(){
			window.open($(this).attr("href"), "myWindow", "width=" + (width * 0.9) + ", height=" + (height * 0.9));
	        return false;
		});
	});
</script>