<?php
$title = "Quản lý đề xuất";
$this->headTitle($title);
?>
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-header row mb-1">
            <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
                <h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
                <div class="row breadcrumbs-top d-inline-block">
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                            <li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                            <li class="breadcrumb-item active">Danh sách</li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                    <a class="btn btn-success pxt-modal" href="javascript:void(0)" title="Thêm dữ liệu" route="<?= $this->url('promotions/offers', ['action' => 'add']) ?>" data-toggle="modal" data-target="#large">
                        <i class="la la-plus-circle"></i> Thêm dữ liệu
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Tìm kiếm</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <?php $this->formSearch->prepare(); ?>
                            <?= $this->form()->openTag($this->formSearch) ?>
                            <div class="form-group col-md-8">
                                <?= $this->formElement($this->formSearch->get('keyword')) ?>
                                <div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                            </div>
                            <div class="form-group col-md-4">
                                <?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                            </div>
                            <?= $this->form()->closeTag($this->formSearch) ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content show">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table bg-white table-bordered table-striped table-hover black">
                                    <thead>
                                        <tr>
                                            <th class="text-center">STT</th>
                                            <th class="text-center">Loại yêu cầu</th>
                                            <th class="text-center">Thông tin đề xuất</th>
                                            <th class="text-center">Thông tin Khách hàng</th>
                                            <th class="text-center">Kết quả xử lý</th>
                                            <th class="text-center">Sự kiện</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        if ($this->arrOffers->getAdapter()->count() > 0) {
                                            $requests = \Promotions\Model\Offers::returnRequest();
                                            $reponses = \Promotions\Model\Offers::returnResponse();
                                            $i = 1;
                                            foreach ($this->arrOffers as $item) {
                                        ?>
                                                <tr>
                                                    <td class="text-center align-middle"><?= $i++; ?></td>
                                                    <td class="text-center align-middle"><strong><?= $requests[$item['request']]; ?></strong></td>
                                                    <td class="align-middle">
                                                        <strong>Nhân viên: </strong><?= $item["staff"] ?><br />
                                                        <strong>Ngày yêu cầu: </strong><?= $item["requested_at"] ?><br />
                                                        <strong>Sản phẩm đề xuất: </strong><?= isset($optionProducts[$item["product_id"]]) ? $optionProducts[$item["product_id"]] : "" ?><br />
                                                        <strong>Nội dung: </strong><?= $item["content"] ?>
                                                    </td>
                                                    <td class="align-middle">
                                                        <strong>Sđt: </strong><?= $item["phone"] ?><br />
                                                        <strong>Yêu cầu: </strong><?= $item["info"] ?>
                                                    </td>
                                                    <td class="align-middle">
                                                        <strong>Kết quả: </strong><?= $reponses[$item["reponse"]] ?><br />
                                                        <?php if ($item["code"] != "") { ?>
                                                            <strong>Mã đơn trả thưởng: </strong><?= $item["code"] ?><br />
                                                        <?php } ?>
                                                        <?php if ($item["reponsed_at"] != "") { ?>
                                                            <strong>Ngày trả: </strong><?= $item["reponsed_at"] ?>
                                                        <?php } ?>
                                                    </td>
                                                    <td class="text-center align-middle">
                                                        <a title="Sửa dữ liệu" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#large" route="<?= $this->url('promotions/offers', ['action' => 'edit', 'id' => $item['id']]) ?>">
                                                            <i class="la la-pencil"></i></a>
                                                        <a title="Bạn muốn xóa?" href="javascript:void(0)" data-toggle="modal" data-target="#defaultSize" class="pxt-modal" route="<?= $this->url('promotions/offers', ['action' => 'delete', 'id' => $item['id']]) ?>">
                                                            <i class="la la-close"></i></a>
                                                    </td>
                                                </tr>
                                            <?php
                                            }
                                        } else {
                                            ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                        }
                                        ?>
                                    </tbody>
                                    <?= $this->paginationControl(
                                        $this->arrOffers,
                                        'Sliding',
                                        'partial/paginator',
                                        ['route' => 'storehouses/index', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                    ) ?>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>