<?php
$title = "Sửa tài khoản";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'index']) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                        		<?php $this->form->prepare(); ?>
                                <?= $this->form()->openTag($this->form) ?>
                                
                                <?php if(isset($this->userId) && $this->userId == '1'){ ?>
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('company_id')) ?>
                                    <?= $this->formElement($this->form->get('company_id')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('company_id')) ?></div>
                                </div>
                                <?php } ?>
                                
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('username')) ?>
                                    <?= $this->formElement($this->form->get('username')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('username')) ?></div>
                                </div>
                                
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('lastname')) ?>
                                    <?= $this->formElement($this->form->get('lastname')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('lastname')) ?></div>
                                </div>
                                
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('firstname')) ?>
                                    <?= $this->formElement($this->form->get('firstname')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('firstname')) ?></div>
                                </div>
                                
                                <div class="form-group col-md-6">
                                    <?= $this->formLabel($this->form->get('gender')) ?>
                                    <div class="demo-radio-button">
                                    <?= $this->formElement($this->form->get('gender')) ?>
                                    </div>
                                </div>
                                
                                <div class="form-group col-md-12 text-center">
                                    <?php
                                        echo $this->formRow($this->form->get('btnSubmit'));
                                    ?>
                                </div>
                                
                                <?=$this->form()->closeTag($this->form)?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>  
<script type="text/javascript">
	$(function() {
		$("#username").focus();
	});
</script>
