<?php
$title = 'Sửa thông tin cá nhân';
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                        		<?php $this->form->prepare(); ?>
                                <?= $this->form()->openTag($this->form) ?>
                                    <div class="form-group col-md-12">
                                        <?= $this->formLabel($this->form->get('firstname')) ?>
                                        <?= $this->formElement($this->form->get('firstname')) ?>
                                        <div class="text-danger"><?= $this->formElementErrors($this->form->get('firstname')) ?></div>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <?= $this->formLabel($this->form->get('lastname')) ?>
                                        <?= $this->formElement($this->form->get('lastname')) ?>
                                        <div class="text-danger"><?= $this->formElementErrors($this->form->get('lastname')) ?></div>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <?= $this->formLabel($this->form->get('gender')) ?>
                                        <div class="demo-radio-button">
                                        <?= $this->formElement($this->form->get('gender')) ?>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-12 row">
                                    	<div class="col-md-8">
                                            <?= $this->formLabel($this->form->get('avatar')) ?>
                                            <?= $this->formElement($this->form->get('avatar')) ?>
                                            <div class="text-danger"><?= $this->formElementErrors($this->form->get('avatar')) ?></div>
                                        </div>
                                    	<div class="col-md-4">
                                            <?php
                                                if(isset($this->valuePost['avatar']) && $this->valuePost['avatar'] != ''){
                                                    echo '<img src="' . URL_UPLOAD . $this->valuePost['avatar'] . '" alt="" height="100px">';
                                                }
                                            ?>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <?= $this->formLabel($this->form->get('password')) ?>
                                        <?= $this->formElement($this->form->get('password')) ?>
                                        <div class="text-danger"><?= $this->formElementErrors($this->form->get('password')) ?></div>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <?= $this->formLabel($this->form->get('re_password')) ?>
                                        <?= $this->formElement($this->form->get('re_password')) ?>
                                        <div class="text-danger"><?= $this->formElementErrors($this->form->get('re_password')) ?></div>
                                    </div>
                                    <div class="form-group col-md-12 text-center">
                                        <?php
                                            echo $this->formRow($this->form->get('btnSubmit'));
                                        ?>
                                    </div>
                                <?=$this->form()->closeTag($this->form)?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>  
<script type="text/javascript">
	$(function() {
		$("#firstname").focus();
	});
</script>