<?php
$title = "Xuất kho";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Dữ liệu để xuất kho</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->form->prepare(); ?>
                             	<?= $this->form()->openTag($this->form) ?>
                             	<div class="form-group col-md-3">
                             		<?= $this->formElement($this->form->get('status')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('status')) ?></div>
                             	</div>

                                <div class="form-group col-md-3">
                             		<?= $this->formElement($this->form->get('exported_at')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('exported_at')) ?></div>
                              	</div>
                                <div class="form-group col-md-3">
                             		<?= $this->formElement($this->form->get('codes')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->form->get('codes')) ?></div>
                              	</div>
                             	<div class="form-group col-md-3">
                                	<?= $this->formRow($this->form->get('btnSubmit')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->form)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>
                             	<div class="form-group col-md-4">
                             		<?= $this->formElement($this->formSearch->get('datetime_begin')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('datetime_begin')) ?></div>
                             	</div>
                                <div class="form-group col-md-4">
                             		<?= $this->formElement($this->formSearch->get('datetime_end')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('datetime_end')) ?></div>
                              	</div>
                             	<div class="form-group col-md-2">
                                	<?= $this->formRow($this->formSearch->get('btnSearch')) ?>
                             	</div>
                             	<div class="form-group col-md-2">
                                	<?= $this->formRow($this->formSearch->get('btnExport')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
					</div>
					<?php if(count($this->arrCodes) > 0){ ?>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                            	<th class="text-center">STT</th>
                                            	<th class="text-center">Ngày xuất</th>
                                            	<th class="text-center">Sản phẩm</th>
                                            	<th class="text-center">Số lượng</th>
                                            	<th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            
                                                $optionProducts = $this->optionProducts;
                                                $i = 1;
                                                foreach($this->arrCodes as $item){
                                        ?>
                                            <tr>
                                            	<td class="align-middle text-center"><?= $i++; ?></td>
                                            	<td class="align-middle text-center"><?= $item['date_at'] ?></td>
                                            	<td class="align-middle text-center"><?= isset($optionProducts[$item['product_id']]) ? $optionProducts[$item['product_id']] : "" ?></td>
                                            	<td class="align-middle text-center"><?= $item['total'] ?></td>
                                            	<td class="align-middle text-center">
													<a href="<?= $this->url('storehouses/exports', ['action' => 'export-excel-date', 'id' => $this->id], ['query' => ['date_at' => $item['date_at'], 'product_id' => $item['product_id']]]) ?>">Xuất chi tiết</</a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
					</div>
					<?php } ?>
                </div>
            </div>
		</div>
	</div>
</div>


<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<script type="text/javascript" src="<?= TEMPS ?>assets/moment.js/2.22.2/moment-with-locales.min.js"></script>
<script type="text/javascript" src="<?= TEMPS ?>assets/moment-timezone/0.5.21/moment-timezone-with-data-2012-2022.min.js"></script>
<script src="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/js/tempusdominus-bootstrap-4.js"></script>
<script type="text/javascript">
$(function () {
	$("#codes").focus();
	$('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss'
   	});
});
</script>