
<?php 
    $this->form->prepare();
    $this->form()->addValidAttribute('route');
?>
        <?= $this->form()->openTag($this->form) ?>
                                
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('key')) ?>
            <?= $this->formElement($this->form->get('key')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('key')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('name')) ?>
            <?= $this->formElement($this->form->get('name')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('name')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('prefix_code')) ?>
            <?= $this->formElement($this->form->get('prefix_code')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('prefix_code')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('prefix_serial')) ?>
            <?= $this->formElement($this->form->get('prefix_serial')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('prefix_serial')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('serial_begin')) ?>
            <?= $this->formElement($this->form->get('serial_begin')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('serial_begin')) ?></div>
        </div>
        
        <div class="form-group col-md-12 text-center">
    		<button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    		<?= $this->formRow($this->form->get('btnSubmit')) ?>
		</div>
        <?=$this->form()->closeTag($this->form)?>
