<?php
$title = "Sửa cấu hình layout";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="<?= $this->url($this->route, ['action' => 'layouts', 'id' => $this->companyId]) ?>">Danh sách</a></li>
                          	<li class="breadcrumb-item active"><?= $title ?></li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                	&nbsp;
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                    			<?php $this->form->prepare(); ?>
                            	<?= $this->form()->openTag($this->form) ?>
                                
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('key')) ?>
                                    <?= $this->formElement($this->form->get('key')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('key')) ?></div>
                                </div>
                                
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('layout')) ?>
                                    <?= $this->formElement($this->form->get('layout')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('layout')) ?></div>
                                </div>
                                
                                <div class="form-group col-md-12">
                                    <?= $this->formLabel($this->form->get('content')) ?>
                                    <?= $this->formElement($this->form->get('content')) ?>
                                    <div class="text-danger"><?= $this->formElementErrors($this->form->get('content')) ?></div>
                                </div>
                                
                                <div class="form-group col-md-12 text-center">
                                    <?= $this->formRow($this->form->get('btnSubmit')) ?>
                                </div>
                                
                                <?= $this->form()->closeTag($this->form) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<script src="<?= TEMPS ?>assets/ckeditor/full/ckeditor.js"></script>
<script src="<?= TEMPS ?>assets/ckfinder/ckfinder.js"></script>
<script>
	CKEDITOR.replace( 'content', {
        height: 400,
		allowedContent: true,
        extraPlugins: 'ckawesome',
    });
</script>