        <?php 
            $this->form->prepare();
            $this->form()->addValidAttribute('route');
        ?>
        <?= $this->form()->openTag($this->form) ?>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('per_page')) ?>
            <?= $this->formElement($this->form->get('per_page')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('per_page')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('per_pages')) ?>
            <?= $this->formElement($this->form->get('per_pages')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('per_pages')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('page_range')) ?>
            <?= $this->formElement($this->form->get('page_range')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('page_range')) ?></div>
        </div>
		
        <div class="form-group col-md-12 text-center">
    		<button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    		<?= $this->formRow($this->form->get('btnSubmit')) ?>
		</div>
        <?=$this->form()->closeTag($this->form)?>
