        <?php 
            $this->form->prepare();
            $this->form()->addValidAttribute('route');
        ?>
        <?= $this->form()->openTag($this->form) ?>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('time_limit_supplies_ins')) ?>
            <?= $this->formElement($this->form->get('time_limit_supplies_ins')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('time_limit_supplies_ins')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('time_limit_supplies_outs')) ?>
            <?= $this->formElement($this->form->get('time_limit_supplies_outs')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('time_limit_supplies_outs')) ?></div>
        </div>
        
        <div class="form-group col-md-12">
            <?= $this->formLabel($this->form->get('time_limit_proposal_details')) ?>
            <?= $this->formElement($this->form->get('time_limit_proposal_details')) ?>
            <div class="text-danger"><?= $this->formElementErrors($this->form->get('time_limit_proposal_details')) ?></div>
        </div>
		
        <div class="form-group col-md-12 text-center">
    		<button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    		<?= $this->formRow($this->form->get('btnSubmit')) ?>
		</div>
        <?=$this->form()->closeTag($this->form)?>
