<!-- <script src="<?= TEMPS ?>app-assets/vendors/js/vendors.min.js"></script> -->

<link rel="stylesheet" type="text/css" href="<?= TEMPS ?>app-assets/vendors/css/forms/selects/select2.min.css">
<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">

<?php 
    $this->form->prepare();
    $this->form()->addValidAttribute('route');
?>
<?= $this->form()->openTag($this->form) ?>
<div class="form-group col-md-6">
    <?= $this->formLabel($this->form->get('code')) ?>
    <?= $this->formElement($this->form->get('code')) ?>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('code')) ?></div>
</div>

<div class="form-group col-md-6">
    <?= $this->formLabel($this->form->get('company_id')) ?>
    <?= $this->formElement($this->form->get('company_id')) ?>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('company_id')) ?></div>
</div>

<div class="form-group col-md-6">
    <?= $this->formLabel($this->form->get('addresses_id')) ?>
    <?= $this->formElement($this->form->get('addresses_id')) ?>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('addresses_id')) ?></div>
</div>

<div class="form-group col-md-6">
    <?= $this->formLabel($this->form->get('surrogates_id')) ?>
    <?= $this->formElement($this->form->get('surrogates_id')) ?>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('surrogates_id')) ?></div>
</div>

<div class="form-group col-md-6">
    <?= $this->formLabel($this->form->get('number_order')) ?>
    <?= $this->formElement($this->form->get('number_order')) ?>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('number_order')) ?></div>
</div>

<div class="form-group col-md-6">
    <?= $this->formLabel($this->form->get('delivery_request')) ?>
    <?= $this->formElement($this->form->get('delivery_request')) ?>
    <div class="text-danger"><?= $this->formElementErrors($this->form->get('delivery_request')) ?></div>
</div>


<div class="form-group col-md-12 text-center">
    <button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    <?= $this->formRow($this->form->get('btnSubmit')) ?>
</div>
<?=$this->form()->closeTag($this->form)?>


<script src="<?= TEMPS ?>assets/pxt.js"></script>
<script src="<?= TEMPS ?>app-assets/vendors/js/forms/select/select2.full.min.js"></script>
<script src="<?= TEMPS ?>app-assets/js/scripts/forms/select/form-select2.min.js"></script>
<script type="text/javascript">
$(function () {
    $("#company_id").bind("change", function(){
        var urlAddresses = "<?= $this->url('companies/orders', ['action' => 'select-addresses']) ?>";
        var urlSurrogates = "<?= $this->url('companies/orders', ['action' => 'select-surrogates']) ?>";
        var id = $(this).val();
        $.post(urlAddresses, { "id" : id }, function(data){
            if(data != ''){
                $("#addresses_id").html(data);
            }else{
                alert('Có lỗi trong quá trình xử lý, đề nghị liên hệ Admin!');
            }
        });
        $.post(urlSurrogates, { "id" : id }, function(data){
            if(data != ''){
                $("#surrogates_id").html(data);
            }else{
                alert('Có lỗi trong quá trình xử lý, đề nghị liên hệ Admin!');
            }
        });
    });
    $('.select2').select2({dropdownParent: $('#xlarge')});
});
</script>

<script type="text/javascript">
$(function () {
    $('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss',
   	});
});
</script>
