<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<?php
$title = "Quản lý đơn hàng";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                      	<a class="btn btn-success pxt-modal" href="javascript:void(0)" title="Thêm dữ liệu" 
                      		route="<?= $this->url('companies/orders', ['action' => 'add']) ?>" data-toggle="modal" data-target="#xlarge">
                      		<i class="la la-plus-circle"></i> Thêm dữ liệu
                      	</a>
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>

                                <!-- <div class="form-group col-md-3">
                             		<?= $this->formElement($this->formSearch->get('datetime_begin')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('datetime_begin')) ?></div>
                             	</div>
                                 <div class="form-group col-md-3">
                             		<?= $this->formElement($this->formSearch->get('datetime_end')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('datetime_end')) ?></div>
                             	</div> -->

                                <div class="form-group col-md-4">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-1">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>

                                <!-- <div class="form-group col-md-1">
                                	<?= $this->formRow($this->formSearch->get('btnExport')) ?>
                             	</div> -->
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <th class="text-center">Mã hợp đồng</th>
                                                <th class="text-center">Khách hàng</th>
                                                <th class="text-center">Số lượng</th>
                                                <th class="text-center">Ngày tạo</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrOrders->getAdapter()->count() > 0){
                                                $i = 1;
                                                $optionCompanies = $this->optionCompanies;
                                                foreach($this->arrOrders as $item){
                                        ?>
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                            	<td class="text-center align-middle"><?= $item['code'] ?></td>
                                            	<td class="align-middle"><?= $optionCompanies[$item['company_id']] ?></td>
                                                <td class="text-center align-middle"><?= $item['number_order'] ?></td>
                                                <td class="text-center align-middle"><?= $item['created_at']; ?></td>
                                                <td class="text-center align-middle">
                                                    <a title="Sửa dữ liệu" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                    	route="<?= $this->url('companies/orders', ['action' => 'edit', 'id' => $item['id']]) ?>">
    													<i class="la la-pencil"></i></a>
                                                    <a title="Chi tiết đơn hàng <?= $item['code']?>" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#large"
                                                        route="<?= $this->url('companies/orders', ['action' => 'iframe-order-details', 'id' => $item['id']]) ?>">
                                                        <i class="la la-list-alt"></i></a>
                                                    <a title="Chi tiết nhiệm vụ <?= $item['code']?>" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                        route="<?= $this->url('companies/orders', ['action' => 'iframe-mission-details', 'id' => $item['id']]) ?>">
                                                        <i class="la la-tasks"></i></a>
                                                    <a title="Bạn muốn xóa '<?= $item['code']; ?>'?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('companies/orders', ['action' => 'delete', 'id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrOrders,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'companies/orders', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function () {
	$("#codes").focus();
	$('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss'
   	});
});
</script>