<?php 
    $this->form->prepare();
    $this->form()->addValidAttribute('route');
    $checkRelationship = $this->checkRelationship;
?>
        <?= $this->form()->openTag($this->form) ?>
        <?php
        if(!empty($checkRelationship)){
        ?>
        <div class="form-group col-md-12">
        	<?= isset($checkRelationship['groups_positions_users']) ? "Chức vụ '" . $this->valueCurrent['name'] . "' đã có liên kết với 'Phân phòng ban cho nhân viên', nếu xoá thì tất cả chức vụ và bộ phận tương ứng được phân cho tài khoản sẽ bị xoá!<br />" : "" ?>
		</div>
        <div class="form-group col-md-12 text-center">
    		<h3>Bạn có muốn xoá?</h3>
		</div>
        <?php
        }
        ?>
        <div class="form-group col-md-12 text-center">
    		<button type="button" class="btn btn-default " data-dismiss="modal" id="pxt-cancel">Đóng</button>
    		<?= $this->formRow($this->form->get('btnSubmit')) ?>
		</div>
        <?=$this->form()->closeTag($this->form)?>


