<?php
$title = "Quản lý hóa đơn";
$this->headTitle($title);

?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                    <a class="btn btn-success pxt-modal" href="javascript:void(0)" title="Thêm dữ liệu" data-toggle="modal" data-target="#defaultSize" 
                    route = "<?= $this->url($this->route, ['action' => 'add','agentid'=>$this->agentId]) ?>">
                    <i class="la la-plus-circle"></i> Thêm dữ liệu
                    </a>
                </div>
            </div>
		</div>
    </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                			<div class="card-body">
                            	<?php //$this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>
                                <div class="form-group col-md-8">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-4">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
            			
                        
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <th class="text-center">Đơn hàng</th>
                                                <th class="text-center">Đại lý</th>
                                                <th class="text-center">Tài khoản tạo</th>
                                                <th class="text-center">Ngày tạo</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrBills->getAdapter()->count() > 0){
                                                $i = 1;
                                                foreach($this->arrBills as $item){
                                        ?>
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                            	<td class="align-middle"><?= $item['name'] ?></td>
                                                <td class="text-center align-middle"><?= isset($optionAgents[$item['agent_id']]) ? $optionAgents[$item['agent_id']] : "Không xác định"; ?></td>
                                                <td class="text-center align-middle"><?= isset($optionUsers[$item['user_id']]) ? $optionUsers[$item['user_id']] : "Không xác định"; ?></td>
                                                <td class="text-center align-middle"><?= $item['exported_at']; ?></td>
                                                <td class="text-center align-middle">
                                                    <a title="Thêm" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                    	route="<?= $this->url('storehouses/bills', ['action' => 'iframe-add', 'agentid' => $this->agentId,'id' => $item['id']]) ?>">
    													<i class="la la-plus-circle"></i></a>
                                                    <a title="Hóa đơn '<?= $item['name'] ?>'" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#xlarge"
                                                    	route="<?= $this->url('storehouses/bills', ['action' => 'iframe-index', 'agentid' => $this->agentId,'id' => $item['id']]) ?>">
    													<i class="la la-eye"></i></a>
                                                    <a title="Sửa dữ liệu" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('storehouses/bills', ['action' => 'edit','agentid'=>$this->agentId ,'id' => $item['id']]) ?>">
    													<i class="la la-pencil"></i></a>
                                                    <a title="Bạn muốn xóa '<?= $item['name']; ?>'?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('storehouses/bills', ['action' => 'delete','agentid' => $this->agentId, 'id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Chưa có dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrBills,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'storehouses/bills', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>