
<?php
$title = "Thêm hợp đồng";
$this->headTitle($title);
$valueCurrent = $this->valueCurrent;
$this->form->prepare();
$this->form()->addValidAttribute('route');
?>
<?= $this->form()->openTag($this->form) ?>
<div class="form-group col-md-12">
	<?= $this->formLabel($this->form->get('begined_at')) ?>
	<?= $this->formElement($this->form->get('begined_at')) ?>
	<div class="text-danger"><?= $this->formElementErrors($this->form->get('begined_at')) ?></div>
</div>

<div class="form-group col-md-12">
	<?= $this->formLabel($this->form->get('ended_at')) ?>
	<?= $this->formElement($this->form->get('ended_at')) ?>
	<div class="text-danger"><?= $this->formElementErrors($this->form->get('ended_at')) ?></div>
</div>

<div class="form-group col-md-12">
	<?= $this->formLabel($this->form->get('file')) ?>
	<?= $this->formElement($this->form->get('file')) ?>
	<p class= "description">Chỉ được upload file có định dạng 'pdf'</p>
	<div class="text-danger"><?= $this->formElementErrors($this->form->get('file')) ?></div>
</div>

<div class="form-group col-md-12 text-center">
	<?php
		echo $this->formRow($this->form->get('btnSubmit'));
	?>
</div>
<?=$this->form()->closeTag($this->form)?>

<link rel="stylesheet" href="<?= TEMPS ?>assets/font-awesome/css/font-awesome.css" />
<link href="<?= TEMPS ?>assets/bootstrap-4-datetimepicker/css/tempusdominus-bootstrap-4.css" rel="stylesheet">
<script src="<?= TEMPS ?>assets/pxt.js"></script>
<script type="text/javascript">
$(function () {
	$("#codes").focus();
	$('.datetimepicker-input').datetimepicker({
       	format: 'DD/MM/YYYY HH:mm:ss'
   	});
});
</script>