<style>
    .description{
        font-size: 13px;
        font-style: italic;
    }
</style>
<?php
$title = "Quản lý hợp đồng";
$this->headTitle($title);
$valueCurrent = $this->valueCurrent;
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title ?> - <?= $valueCurrent['lastname'] ?> <?= $valueCurrent['firstname'] ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title ?></a></li>
                          	<li class="breadcrumb-item active">Danh sách</li>
                		</ol>
              		</div>
            	</div>
          	</div>
            <div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                    <a class="btn btn-success pxt-modal" title="Thêm hợp đồng <?= $valueCurrent['lastname'] ?> <?= $valueCurrent['firstname'] ?>" href="javascript:void(0)" data-toggle="modal" data-target="#defaultSize"
                    route="<?= $this->url("admin/labour-contracts", ['action' => 'add','id' =>$this->userId]) ?>">
                        <i class="la la-plus-circle"></i> Thêm dữ liệu
                    </a>
                </div>
            </div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>
                                <div class="form-group col-md-8">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-4">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <th class="text-center">Ngày bắt đầu</th>
                                                <th class="text-center">Ngày kết thúc</th>
                                                <th class="text-center">Ngày tạo</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrContracts->getAdapter()->count() > 0){
                                                $i = 1;
                                                foreach($this->arrContracts as $item){
                                        ?>
                                        
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                            	<td class="text-center align-middle"><?= $item['begined_at'] ?></td>
                                            	<td class="text-center align-middle"><?= ($item['ended_at'] != null) ? $item['ended_at'] : "Vô thời hạn"?></td>
                                                <td class="text-center align-middle"><?= $item['created_at']; ?></td>
                                                <td class="text-center align-middle">
                                                    <a class="pxt-modal" title="Xem hợp đồng" href="javascript:void(0)" data-toggle="modal" data-target="#xlarge"
                                                        route="<?= $this->url('admin/labour-contracts', ['action' => 'view', 'id' => $this->userId, 'labour-contracts_id' => $item['id']]) ?>">
                                                        <i class="la la-eye"></i>
                                                    </a>
                                                    <a title="Sửa hợp đồng  <?= $valueCurrent['lastname'] ?> <?= $valueCurrent['firstname'] ?>" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    route="<?= $this->url('admin/labour-contracts', ['action' => 'edit','id' => $this->userId, 'labour-contracts_id' => $item['id']]) ?>">
    													<i class="la la-pencil"></i></a>

                                                    <a title="Bạn muốn xóa" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('admin/labour-contracts', ['action' => 'delete', 'id' => $this->userId, 'labour-contracts_id' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrContracts,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'admin/labour-contracts', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
