<?php 
    $companyCurrent = [];
    if(isset($this->companyCurrent)){
        $companyCurrent = $this->companyCurrent;
    }
    $settingDisplay = [];
    if(isset($companyCurrent['setting_display'])){
        $settingDisplay = json_decode($companyCurrent['setting_display'], true);
    }
    // display css
    echo isset($settingDisplay['style']) ? ("<style>" . $settingDisplay['style'] . "</style>") : "";
?>
<?php if(isset($settingDisplay['logo'])){ ?>
<p style="text-align: center; margin-top: 10px;"><img src="<?= $settingDisplay['logo'] ?>" width="60%" alt=""></p>
<?php } ?>
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100 p-t-5 p-b-20">
    		<?php $this->form->prepare(); ?>
            <?= $this->form()->openTag($this->form) ?>
            <div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('fullname')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('fullname')) ?></div>
            </div>
            <div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('phone')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('phone')) ?></div>
            </div>
			<div class="container-login100-form-btn">
				<?= $this->formRow($this->form->get('btnSubmit')) ?>
			</div>
        	<?=$this->form()->closeTag($this->form)?>
		</div>
	</div>
</div>