<?php 
    $displays = $this->displays;
?>
<?php if(isset($displays['logo'])){ ?>
<p style="text-align: center; margin-top: 10px;"><img src="<?= URL_UPLOAD . $displays['logo'] ?>" width="60%" alt=""></p>
<?php } ?>
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100 p-t-5 p-b-20">
    		<?php $this->form->prepare(); ?>
            <?= $this->form()->openTag($this->form) ?>
            <div class="wrap-input100 validate-input m-t-0 m-b-35">
				<h4 style="text-align: center;">Quý khách vui lòng nhập SĐT để kích hoạt bảo hành</h4>
			</div>
            <div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('phone')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('phone')) ?></div>
            </div>
			<div class="container-login100-form-btn">
				<?= $this->formRow($this->form->get('btnSubmit')) ?>
			</div>
        	<?=$this->form()->closeTag($this->form)?>
		</div>
	</div>
</div>