<?php 
    $display = [];
    if(isset($this->displays)){
        $display = $this->displays;
    }
    // display css
    echo isset($display['style']) ? ("<style>" . $display['style'] . "</style>") : "";
?>
<?php if(isset($display['logo'])){ ?>
<p style="text-align: center; margin-top: 10px;"><img src="<?= URL_UPLOAD . $display['logo'] ?>" width="60%" alt=""></p>
<?php } ?>
<p style="text-align: center; margin-top: 10px; font-size: 16px; font-weight: bold;">Để tra xuất thông tin sản phẩm dễ dàng chính xác & nhanh chóng nhất, bãn hãy nhập thông tin vào ô bên dưới</p>
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100 p-t-5 p-b-20">
    		<?php $this->form->prepare(); ?>
            <?= $this->form()->openTag($this->form) ?>
            <?php /* ?><div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('fullname')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('fullname')) ?></div>
            </div><?php */ ?>
            <div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('phone')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('phone')) ?></div>
            </div>
            <?php /* ?><div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('address')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('address')) ?></div>
            </div><?php */ ?>
			<div class="container-login100-form-btn">
				<?= $this->formRow($this->form->get('btnSubmit')) ?>
			</div>
        	<?=$this->form()->closeTag($this->form)?>
		</div>
	</div>
</div>

<p style="text-align: center; margin-top: 10px; font-size: 15px; ">
    <strong>Lưu ý:</strong> Mã QR code được đồng bộ cùng mã PIN trên phần phủ cào SMS, bạn hãy sử dụng 1 trong 2 hình thức này để kiểm tra thông tin sản phẩm.<br />
    Bạn có thể tra cứu thông tin sản phẩm tối đa 3 lần, và chỉ áp dụng cho 1 số điện thoại duy nhất.
</p>
