<?php 
    $display = [];
    if(isset($this->display)){
        $display = $this->display;
    }
    // display css
    echo isset($display['style']) ? ("<style>" . $display['style'] . "</style>") : "";
?>
<?php if(isset($display['logo'])){ ?>
<p style="text-align: center; margin-top: 10px;"><img src="<?= URL_UPLOAD . $display['logo'] ?>" width="60%" alt=""></p>
<?php } ?>
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100 p-t-5 p-b-20">
    		<?php $this->form->prepare(); ?>
            <?= $this->form()->openTag($this->form) ?>
            <div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('fullname')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('fullname')) ?></div>
            </div>
            <div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('phone')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('phone')) ?></div>
            </div>
            <div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('cities_id')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('cities_id')) ?></div>
            </div>
			<div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('type_agent')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('type_agent')) ?></div>
            </div>
			<div class="wrap-input100 validate-input m-t-0 m-b-35">
                <?= $this->formElement($this->form->get('code')) ?>
                <div class="text-danger"><?= $this->formElementErrors($this->form->get('code')) ?></div>
            </div>
			<div class="container-login100-form-btn">
				<?= $this->formRow($this->form->get('btnSubmit')) ?>
			</div>
        	<?=$this->form()->closeTag($this->form)?>
		</div>
	</div>
</div>