<?php
$title = "Địa chỉ khách hàng";
$this->headTitle($title);
?>
<div class="app-content content">
	<div class="content-wrapper">
		<div class="content-header row mb-1">
          	<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            	<h3 class="content-header-title mb-0 d-inline-block"><?= $title . " " . $this->companyId ?></h3>
            	<div class="row breadcrumbs-top d-inline-block">
              		<div class="breadcrumb-wrapper col-12">
                		<ol class="breadcrumb">
                          	<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                          	<li class="breadcrumb-item"><a href="#"><?= $title . " " . $this->companyId ?></a></li>
                          	<li class="breadcrumb-item active"><a href="<?= $this->url('companies/addresses', ['action' => 'index','id' => $this->companyId]) ?>">Danh sách</a> </li>
                		</ol>
              		</div>
            	</div>
          	</div>
       		<div class="content-header-right col-md-6 col-12">
                <div class="btn-group float-md-right">
                    <a class="btn btn-success pxt-modal" href="<?= $this->url('companies/addresses', ['action' => 'add','id' => $this->companyId]) ?>" title="Thêm dữ liệu">
                        <i class="la la-plus-circle"></i> Thêm dữ liệu
                    </a>
                  	
                </div>
			</div>
        </div>
        <div class="content-body">
			<div class="row">
    			<div class="col-12">
        			<div class="card">
        				<div class="card-header">
                            <h4 class="card-title">Tìm kiếm</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                </ul>
                            </div>
                        </div>
            			<div class="card-content collapse show">
                			<div class="card-body">
                            	<?php $this->formSearch->prepare(); ?>
                             	<?= $this->form()->openTag($this->formSearch) ?>
                                <div class="form-group col-md-8">
                             		<?= $this->formElement($this->formSearch->get('keyword')) ?>
                                 	<div class="text-danger"><?= $this->formElementErrors($this->formSearch->get('keyword')) ?></div>
                              	</div>
                             	<div class="form-group col-md-4">
                                	<?= $this->formRow($this->formSearch->get('btnSubmit')) ?>
                             	</div>
                            	<?=$this->form()->closeTag($this->formSearch)?>
                            </div>
                        </div>
                    </div>
        			<div class="card">
            			<div class="card-content show">
                			<div class="card-body">
                                <div class="table-responsive">
                                    <table class="table bg-white table-bordered table-striped table-hover black">
                                        <thead>
                                            <tr>
                                                <th class="text-center">STT</th>
                                                <th class="text-center">Loại</th>
                                                <th class="text-center">Địa chỉ</th>
                                                <th class="text-center">Số điện thoại</th>
                                                <th class="text-center">Trạng thái</th>
                                                <th class="text-center">Ngày tạo</th>
                                                <th class="text-center">Sự kiện</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                            if($this->arrAddresses->getAdapter()->count() > 0){
                                                $i = 1;
                                                //\Customers\Model\Addresses::returnIsType();
                                                $arrIsType = \Companies\Model\Addresses::returnIsType();
                                                foreach($this->arrAddresses as $item){
                                        ?>
                                            <tr>
                                            	<td class="text-center align-middle"><?= $i++; ?></td>
                                            	<td class="text-center align-middle"><?= isset($arrIsType[$item['is_type']]) ? $arrIsType[$item['is_type']] : 'Không tìm thấy!' ?></td>
                                            	<td class="align-middle"><?= $item['address'] ?></td>
                                                <td class="align-middle"><?= $item['phone'] ?></td>
                                                <td class="text-center align-middle"><?= isset($item['status']) ? \Companies\Model\Addresses::getStatus()[$item['status']] : ''?></td>
                                                <td class="text-center align-middle"><?= $item['created_at']; ?></td>
                                                <td class="text-center align-middle">
                                                    <a title="Sửa địa chỉ '<?= $item['address'] ?>'" href="<?= $this->url('companies/addresses', ['action' => 'edit', 'id' => $this->companyId, 'addressid' =>$item['id']]) ?>">
    													<i class="la la-pencil"></i></a>
                                                    <a title="Bạn muốn xóa địa chỉ'<?= $item['address'] ?>'?" href="javascript:void(0)" class="pxt-modal" data-toggle="modal" data-target="#defaultSize"
                                                    	route="<?= $this->url('companies/addresses', ['action' => 'delete', 'id' => $this->companyId, 'addressid' => $item['id']]) ?>">
    													<i class="la la-close"></i></a>
												</td>
                                            </tr>
                                        <?php
                                                }
                                            }else{
                                        ?>
                                            <tr>
                                                <td colspan="100" class="text-center">Không tìm thấy dữ liệu</td>
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                        </tbody>
										<?= $this->paginationControl(
                                            $this->arrAddresses,
                                            'Sliding',
                                            'partial/paginator',
                                            ['route' => 'companies/addresses', 'contentPaginator' => $this->contentPaginator, 'queries' => $this->queries]
                                        ) ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
